"""G-code -> layer data for the app's preview (SL-06/07)."""
from __future__ import annotations

import json
import math
import time

from printshare.gcode_preview import bed_size, build, parse

ORCA = """; generated by OrcaSlicer 2.4.2
M83 ; relative extrusion
G90
G1 Z0.3 F720
;TYPE:Custom
G1 X0 Y0 F3000
G1 X50 Y0 E2.5 ; prime line
G1 E-.8 F1800 ; retract
;LAYER_CHANGE
;Z:0.2
;HEIGHT:0.2
G1 Z.2
;TYPE:Outer wall
G1 X10 Y10 F9000
G1 E.8
G1 X20 Y10 E.5
G1 X20 Y20 E.5
G1 X10 Y20 E.5
G1 X10 Y10 E.5
;TYPE:Sparse infill
G1 X12 Y12 ; travel
G1 X18 Y18 E.3
G1 Z.6 ; z hop
G1 X12 Y18
G1 Z.2
G1 X18 Y12 E.3
;LAYER_CHANGE
;Z:0.4
G1 Z.4
;TYPE:Outer wall
G1 X30 Y30
G2 X40 Y30 I5 J0 E.8 ; half circle (clockwise, below the chord)
"""


def test_layers_types_and_travel():
    d = parse(ORCA.splitlines())
    assert d["types"] == ["Custom", "Outer wall", "Sparse infill"]
    assert [lay["z"] for lay in d["layers"]] == [0.2, 0.4]   # prime line belongs to layer 1, no z-hop layer
    first = d["layers"][0]["paths"]
    u = d["unit"]
    assert first[0] == [0, 0, 0, 0, 50 * u, 0]                          # prime line (Custom, filament 1)
    square = first[1]
    assert square[:2] == [1, 0] and square[2:4] == [10 * u, 10 * u] and square[-2:] == [10 * u, 10 * u]
    assert len(square) == 2 + 2 * 5                                    # closed square, 5 points
    infill = [p for p in first if p[0] == 2]
    assert len(infill) == 2                                            # travel and z-hop split the lines
    assert infill[0][2:] == [12 * u, 12 * u, 18 * u, 18 * u] and infill[1][2:] == [12 * u, 18 * u, 18 * u, 12 * u]
    assert d["bounds"] == [10.0, 10.0, 40.0, 35.0]   # without the prime line; the arc reaches y=35


def test_arc_is_linearised_in_the_right_direction():
    d = parse(ORCA.splitlines())
    arc = d["layers"][1]["paths"][0]
    pts = list(zip(arc[2::2], arc[3::2]))
    u = d["unit"]
    assert pts[0] == (30 * u, 30 * u) and pts[-1] == (40 * u, 30 * u)
    assert len(pts) > 8
    assert max(p[1] for p in pts) > 30 * u + 4 * u   # clockwise from the left point runs above the centre
    assert all(abs(math.dist(p, (35 * u, 30 * u)) - 5 * u) <= 1.5 for p in pts)


def test_absolute_extrusion_and_retraction():
    g = """M82
G92 E0
;LAYER_CHANGE
;Z:0.2
G1 X0 Y0 Z0.2
;TYPE:Inner wall
G1 X10 Y0 E1
G1 E0.2      ; retract
G1 X10 Y10   ; travel
G1 E1        ; unretract
G1 X0 Y10 E2
G92 E0
G1 X0 Y0 E1
"""
    d = parse(g.splitlines())
    paths = d["layers"][0]["paths"]
    assert len(paths) == 2 and paths[1][2:] == [200, 200, 0, 200, 0, 0]   # continues after G92 reset


def test_simplification_keeps_shape():
    lines = [";LAYER_CHANGE", ";Z:0.2", "M83", "G1 X0 Y0 Z0.2", ";TYPE:Outer wall"]
    lines += [f"G1 X{i * 0.05:.2f} Y0 E0.01" for i in range(1, 401)]   # 20 mm straight line in 400 steps
    lines += ["G1 X20 Y5 E0.2"]
    path = parse(lines)["layers"][0]["paths"][0]
    assert path == [0, 0, 0, 0, 400, 0, 400, 100]


def test_large_print_is_fast_and_compact(tmp_path):
    lines = ["M83"]
    for n in range(1, 301):                                  # 300 layers, cylinder + zigzag infill
        z = round(0.2 * n, 2)
        lines += [";LAYER_CHANGE", f";Z:{z}", f"G1 Z{z}"]
        for w, r in enumerate((20, 19.55, 19.1)):
            lines += [";TYPE:" + ("Outer wall" if w == 0 else "Inner wall"), f"G1 X{100 + r} Y100"]
            lines += [f"G1 X{100 + r * math.cos(a / 180 * math.pi):.3f} Y{100 + r * math.sin(a / 180 * math.pi):.3f} E0.02"
                      for a in range(2, 362, 2)]
        lines += [";TYPE:Sparse infill", "G1 X82 Y82"]
        lines += [f"G1 X{82 + (i % 2) * 36} Y{82 + i * 0.9:.2f} E0.1" for i in range(40)]
    g = tmp_path / "cyl.gcode"
    g.write_text("\n".join(lines))
    t0 = time.time()
    d = build(g, bed_size(["0x0", "256x0", "256x256", "0x256"]))
    took = time.time() - t0
    size = len(json.dumps(d, separators=(",", ":")))
    assert len(d["layers"]) == 300 and d["bed"] == [256.0, 256.0]
    assert took < 5, took
    assert size < 2_500_000, size
    assert (tmp_path / "cyl.preview.json").is_file()                  # cached
    assert build(g)["layers"][0] == d["layers"][0]


def test_bed_size():
    assert bed_size(["0x0", "256x0", "256x256", "0x256"]) == (256.0, 256.0)
    assert bed_size(["-5x-5", "180x-5", "180x180", "-5x180"]) == (185.0, 185.0)
    assert bed_size(None) is None and bed_size(["junk"]) is None


def test_tools_and_filament_colours():
    g = """; generated by OrcaSlicer
M83
;LAYER_CHANGE
;Z:0.2
G1 Z0.2
;TYPE:Outer wall
T0
G1 X0 Y0
G1 X10 Y0 E1
M6211 T1 L200 ; CANVAS change on stock firmware (not a tool command itself)
T1
G1 X10 Y10 E1
G1 X0 Y10 E1
; extruder_colour = #018001;#018001
; filament_colour = #ff0000;#00AE42
"""
    d = parse(g.splitlines())
    assert d["version"] == 2 and d["filament_colors"] == ["#FF0000", "#00AE42"]
    paths = d["layers"][0]["paths"]
    assert [p[1] for p in paths] == [0, 1]                  # the colour change splits the line
    assert paths[1][2:] == [200, 0, 200, 200, 0, 200]


def test_old_cache_is_rebuilt(tmp_path):
    g = tmp_path / "a.gcode"
    g.write_text(ORCA)
    (tmp_path / "a.preview.json").write_text(json.dumps({"version": 1, "layers": []}))
    import os
    os.utime(g, (1, 1))
    assert len(build(g)["layers"]) == 2
