"""Preview images in the G-code for the printer's screen (the Orca CLI makes none without a display)."""
from __future__ import annotations

import base64
import io
import re

from PIL import Image

from printshare import thumbnails

GCODE = """; HEADER_BLOCK_START
; generated by OrcaSlicer 2.4.2
; HEADER_BLOCK_END

; EXECUTABLE_BLOCK_START
;LAYER_CHANGE
;Z:0.2
;TYPE:Outer wall
G1 X10 Y10 E1
G1 X30 Y10 E2
G1 X30 Y30 E3
G1 X10 Y30 E4
G1 X10 Y10 E5
;LAYER_CHANGE
;Z:0.4
;TYPE:Top surface
G1 X12 Y12 E6
G1 X28 Y28 E7
; filament_colour = #FF0000
"""


def pixels(im):
    raw = im.convert("RGBA").tobytes()
    return [tuple(raw[i:i + 4]) for i in range(0, len(raw), 4)]


def blocks_of(text):
    return re.findall(r"; (thumbnail\w*) begin (\d+)x(\d+) (\d+)\n((?:; .*\n)+?); \1 end", text)


def test_specs():
    assert thumbnails.specs({"thumbnails": ["16x16/QOI", "640x480/PNG"]}) == [(16, 16, "QOI"), (640, 480, "PNG")]
    assert thumbnails.specs({"thumbnails": ["144x144"], "thumbnails_format": "PNG"}) == [(144, 144, "PNG")]
    assert thumbnails.specs({"thumbnails": "96x96/JPG, 300x300"}) == [(96, 96, "JPG"), (300, 300, "PNG")]
    assert thumbnails.specs({}) == thumbnails.DEFAULT_SPECS
    assert thumbnails.specs({"thumbnails": ["5000x5000/PNG", "10x10/COLPIC"]}) == thumbnails.DEFAULT_SPECS


def test_qoi_matches_pillows_reader():
    img = Image.new("RGBA", (37, 23), (0, 0, 0, 0))
    for x in range(37):
        for y in range(23):
            img.putpixel((x, y), (x * 7 % 256, y * 11 % 256, (x * y) % 256, 255 if (x + y) % 5 else 128))
    img.paste((10, 20, 30, 255), (0, 0, 10, 10))                     # runs
    decoded = Image.open(io.BytesIO(thumbnails.qoi(img))).convert("RGBA")
    assert pixels(decoded) == pixels(img)


def test_add_to_gcode(tmp_path):
    g = tmp_path / "part.gcode"
    g.write_text(GCODE)
    n = thumbnails.add_to_gcode(g, {"thumbnails": ["16x16/QOI", "300x300/PNG", "96x96/JPG"]})
    text = g.read_text()
    assert n == 3 and text.startswith("; HEADER_BLOCK_START")
    assert text.index("; THUMBNAIL_BLOCK_START") > text.index("; HEADER_BLOCK_END") < text.index("; EXECUTABLE_BLOCK_START")
    found = blocks_of(text)
    assert [(b[0], b[1], b[2]) for b in found] == [("thumbnail_QOI", "16", "16"), ("thumbnail", "300", "300"),
                                                   ("thumbnail_JPG", "96", "96")]
    for kind, w, h, length, body in found:
        b64 = "".join(line[2:] for line in body.splitlines())
        assert len(b64) == int(length) and all(len(line) <= 80 for line in body.splitlines())
        im = Image.open(io.BytesIO(base64.b64decode(b64)))
        assert im.size == (int(w), int(h))
    png = Image.open(io.BytesIO(base64.b64decode("".join(line[2:] for line in found[1][4].splitlines())))).convert("RGBA")
    assert any(px[3] and px[0] > px[1] for px in pixels(png))           # red filament drawn
    assert GCODE.split("; HEADER_BLOCK_END\n", 1)[1] in text               # the rest unchanged
    assert thumbnails.add_to_gcode(g, {"thumbnails": ["16x16/PNG"]}) == 0  # never twice


def test_without_header_and_broken(tmp_path):
    g = tmp_path / "plain.gcode"
    g.write_text(GCODE.split("; HEADER_BLOCK_END\n", 1)[1])
    assert thumbnails.add_to_gcode(g, {}) == 2 and g.read_text().startswith("; THUMBNAIL_BLOCK_START")
    empty = tmp_path / "empty.gcode"
    empty.write_text("G28\n")
    assert thumbnails.add_to_gcode(empty, {}) == 0 and empty.read_text() == "G28\n"   # nothing printed: no picture
    assert thumbnails.add_to_gcode(tmp_path / "missing.gcode", {}) == 0                 # never raises
