"""First start without a hand-written config.yaml (Unraid template, Home Assistant add-on).

Two ways to configure PocketPrint3D:
* **Managed**: the printer is set in the Unraid template (PRINTER_* variables) or in the Home Assistant
  add-on options. config.yaml is then regenerated on every start, so changes in the form take effect.
* **File**: no printer in the form -> an existing config.yaml is used unchanged (several printers,
  overrides, `machine_file` …). If there is none yet, an empty one with a token is created.

The access token is kept across restarts: taken from the form, else from the existing config.yaml,
else generated once.
"""
from __future__ import annotations

import json
import logging
import os
import re
import secrets
from pathlib import Path
from typing import Any, Mapping

import yaml

log = logging.getLogger("printshare")

HA_OPTIONS = Path("/data/options.json")
PLATES = ("Textured PEI Plate", "High Temp Plate", "Cool Plate", "Engineering Plate", "Supertack Plate")
DEFAULT_MACHINE = "Elegoo Centauri Carbon 0.4 nozzle"
DEFAULT_PROCESS = "0.20mm Standard @Elegoo CC 0.4 nozzle"
DEFAULT_FILAMENT = "Elegoo PLA @ECC"
HEADER = ("# Generated by PocketPrint3D from the {source} on every start - changes here are overwritten.\n"
          "# To manage this file by hand, remove the printer from the {source} first.\n")
TRUE = ("1", "true", "yes", "on")


def _slug(name: str, taken: set[str]) -> str:
    base = re.sub(r"[^a-z0-9]+", "-", name.lower()).strip("-") or "printer"
    slug, n = base, 2
    while slug in taken:
        slug, n = f"{base}-{n}", n + 1
    taken.add(slug)
    return slug


def simple_printer(p: Mapping[str, Any], taken: set[str]) -> dict[str, Any]:
    """Form fields (name, type, address, login, profiles, plate) -> config.yaml printer entry."""
    from .printers import PRINTER_TYPES
    name = str(p.get("name") or "Printer").strip()
    kind = str(p.get("type") or "elegoo_sdcp").strip()
    address = str(p.get("address") or "").strip().rstrip("/")
    if kind not in PRINTER_TYPES:
        raise ValueError(f"printer type must be one of {', '.join(PRINTER_TYPES)}, not {kind!r}")
    if not address:
        raise ValueError(f"printer {name!r}: address (IP) is missing")
    machine = str(p.get("printer_profile") or "").strip()
    if kind in ("prusalink", "octoprint") and (not machine or machine == DEFAULT_MACHINE):
        # never fall back to the Centauri profile for another printer
        raise ValueError(f"printer {name!r}: printer_profile is required for {kind} - the OrcaSlicer printer "
                         "name, e.g. 'Prusa MK4S 0.4 nozzle' or 'Creality Ender-3 V2 0.4 nozzle'")
    machine = machine or DEFAULT_MACHINE
    slicing: dict[str, Any] = {"machine": machine, "bed_type": p.get("build_plate") or PLATES[0]}
    for key, field_name, default in (("process", "quality_profile", DEFAULT_PROCESS),
                                     ("filament", "filament_profile", DEFAULT_FILAMENT)):
        value = str(p.get(field_name) or "").strip()
        if value:
            slicing[key] = value
        elif machine == DEFAULT_MACHINE:
            slicing[key] = default
        # other printers: config.load_settings takes the machine preset's own defaults
    if slicing["bed_type"] not in PLATES:
        raise ValueError(f"build plate must be one of {', '.join(PLATES)}")
    entry: dict[str, Any] = {"id": _slug(name, taken), "name": name, "type": kind}
    if kind == "elegoo_sdcp":
        entry["host"] = re.sub(r"^https?://", "", address).split("/")[0]
    else:
        entry["url"] = address if re.match(r"^https?://", address) else f"http://{address}"
    if kind == "moonraker" and str(p.get("cosmos", True)).lower() in TRUE:
        slicing["machine_preset"] = "cosmos"
    if p.get("api_key"):
        entry["api_key"] = p["api_key"]
    if kind == "prusalink":
        if p.get("password"):
            entry["password"] = p["password"]
        if p.get("username"):
            entry["username"] = p["username"]
        if not (entry.get("password") or entry.get("api_key")):
            raise ValueError(f"printer {name!r}: PrusaLink needs the password shown on the printer "
                             "(Settings > Network > PrusaLink)")
    if kind == "octoprint" and not entry.get("api_key"):
        raise ValueError(f"printer {name!r}: OctoPrint needs an API key (OctoPrint Settings > Application keys)")
    entry["slicing"] = slicing
    return entry


def env_form(env: Mapping[str, str]) -> dict[str, Any] | None:
    """Unraid template / docker run -e … (one printer)."""
    if not env.get("PRINTER_ADDRESS", "").strip():
        return None
    return {
        "source": "container settings (Unraid template)",
        "api_token": env.get("PRINTSHARE_API_TOKEN", ""),
        "thingiverse_token": env.get("THINGIVERSE_TOKEN", ""),
        "printers": [{
            "name": env.get("PRINTER_NAME", "") or "Centauri Carbon",
            "type": env.get("PRINTER_TYPE", "") or "elegoo_sdcp",
            "address": env["PRINTER_ADDRESS"],
            "cosmos": env.get("PRINTER_COSMOS", "true"),
            "api_key": env.get("PRINTER_API_KEY", ""),
            "password": env.get("PRINTER_PASSWORD", ""),
            "printer_profile": env.get("PRINTER_PROFILE", ""),
            "quality_profile": env.get("QUALITY_PROFILE", ""),
            "filament_profile": env.get("FILAMENT_PROFILE", ""),
            "build_plate": env.get("BUILD_PLATE", ""),
        }],
    }


def ha_form(path: Path = HA_OPTIONS) -> dict[str, Any] | None:
    """Home Assistant add-on options (/data/options.json)."""
    if not path.is_file():
        return None
    opts = json.loads(path.read_text(encoding="utf-8") or "{}")
    return {"source": "add-on configuration (Home Assistant)", "api_token": opts.get("api_token", ""),
            "thingiverse_token": opts.get("thingiverse_token", ""), "printers": opts.get("printers") or [],
            "server_url": opts.get("server_url", ""), "remote_url": opts.get("remote_url", "")}


def apply_addon_options(env: "os._Environ | dict[str, str] | None" = None, ha_options: Path = HA_OPTIONS) -> None:
    """Home Assistant add-on: options that work through the environment (bridge mode, docs/BRIDGE.md)."""
    env = os.environ if env is None else env
    if not ha_options.is_file():
        return
    opts = json.loads(ha_options.read_text(encoding="utf-8") or "{}")
    if opts.get("cloud_bridge"):
        env["PRINTSHARE_BRIDGE"] = "1"
    if str(opts.get("lan_subnet") or "").strip():
        env["PRINTSHARE_LAN_SUBNET"] = str(opts["lan_subnet"]).strip()
    env.setdefault("PRINTSHARE_NAME", "Home Assistant")


def ensure_config(config_path: str | Path, env: Mapping[str, str] | None = None,
                  ha_options: Path = HA_OPTIONS) -> dict[str, Any]:
    """Create or refresh config.yaml; returns {"token", "managed", "printers"} for the start banner."""
    env = os.environ if env is None else env
    path = Path(config_path)
    old: dict[str, Any] = {}
    if path.is_file():
        old = yaml.safe_load(path.read_text(encoding="utf-8")) or {}
    form = ha_form(ha_options) or env_form(env)

    if form and form["printers"]:
        taken: set[str] = set()
        printers = [simple_printer(p, taken) for p in form["printers"]]
        cfg = {k: v for k, v in old.items() if k not in ("printers", "api_token", "thingiverse_token")}
        cfg["api_token"] = form["api_token"] or old.get("api_token") or secrets.token_urlsafe(18)
        cfg["thingiverse_token"] = form["thingiverse_token"] or old.get("thingiverse_token", "")
        cfg["printers"] = printers
        _write(path, HEADER.format(source=form["source"]) + yaml.safe_dump(cfg, sort_keys=False, allow_unicode=True))
        return {"token": cfg["api_token"], "managed": True, "printers": printers}

    if not path.is_file():
        token = (form or {}).get("api_token") or env.get("PRINTSHARE_API_TOKEN") or secrets.token_urlsafe(18)
        _write(path, "# PocketPrint3D configuration - add your printers here (see config-example.yaml)\n"
                     + yaml.safe_dump({"api_token": token, "thingiverse_token": "", "printers": []}, sort_keys=False))
        old = {"api_token": token}
    return {"token": env.get("PRINTSHARE_API_TOKEN") or old.get("api_token", ""), "managed": False,
            "printers": old.get("printers") or []}


def _write(path: Path, text: str) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)
    tmp = path.with_suffix(".tmp")
    tmp.write_text(text, encoding="utf-8")
    tmp.chmod(0o600)
    tmp.replace(path)


def server_url(env: Mapping[str, str] | None = None, ha_options: Path = HA_OPTIONS) -> str:
    """Address the phone should use: explicit setting, else the Home Assistant host IP (best effort)."""
    env = os.environ if env is None else env
    form = ha_form(ha_options) or {}
    url = (form.get("server_url") or env.get("PRINTSHARE_URL") or "").strip()
    if url:
        return url if re.match(r"^https?://", url) else f"http://{url}"
    if env.get("SUPERVISOR_TOKEN"):
        try:
            import httpx
            r = httpx.get("http://supervisor/network/info", timeout=3,
                          headers={"Authorization": f"Bearer {env['SUPERVISOR_TOKEN']}"})
            for iface in r.json()["data"]["interfaces"]:
                addrs = (iface.get("ipv4") or {}).get("address") or []
                if iface.get("primary") and addrs:
                    return f"http://{addrs[0].split('/')[0]}:8484"
        except Exception:  # noqa: BLE001 - the banner then shows instructions instead
            pass
    return ""


def remote_url(env: Mapping[str, str] | None = None, ha_options: Path = HA_OPTIONS) -> str:
    """Optional second address for the app away from home (Tailscale / VPN)."""
    env = os.environ if env is None else env
    url = ((ha_form(ha_options) or {}).get("remote_url") or env.get("PRINTSHARE_REMOTE_URL") or "").strip()
    return "" if not url else url if re.match(r"^https?://", url) else f"http://{url}"


def banner(info: dict[str, Any], url: str, remote: str = "") -> str:
    """Start message for the container log: token and pairing code for the app."""
    lines = ["", "=" * 60, "PocketPrint3D is running on port 8484"]
    names = ", ".join(p.get("name") or p.get("id", "?") for p in info["printers"])
    lines.append(f"Printers: {names}" if names else
                 "No printer configured yet - add one in the container / add-on settings.")
    lines.append(f"Access token: {info['token'] or '(none)'}")
    if os.environ.get("PRINTSHARE_BRIDGE", "").lower() in ("1", "true", "yes"):
        lines.append("PocketPrint3D Cloud: bridge mode on - the pairing code for the app follows below")
    if url:
        from .cli import pairing_link
        lines.append(f"App: scan this code (Settings > Connect server) or enter {url} and the token")
        if remote:
            lines.append(f"     away from home the app uses {remote}")
        lines.append("")
        try:
            import io

            import segno
            buf = io.StringIO()
            segno.make(pairing_link(url, info["token"], remote), error="m").terminal(out=buf, compact=True)
            lines.append(buf.getvalue())
        except Exception:  # noqa: BLE001
            pass
        lines.append(f"Web app: {url}")
    else:
        lines.append("App: enter http://<server-ip>:8484 and the token, or set the server address "
                     "(PRINTSHARE_URL / add-on option server_url) to get a QR code here.")
    lines.append("=" * 60)
    return "\n".join(lines)
