; HEADER_BLOCK_START
; generated by OrcaSlicer 2.4.2 on 2026-10-02 at 14:25:44
; total layer number: 123
; filament_density: 1.25
; filament_diameter: 1.75
; max_z_height: 25.00
; filament: 1
; HEADER_BLOCK_END

; THUMBNAIL_BLOCK_START
; thumbnail begin 144x144 27132
; iVBORw0KGgoAAAANSUhEUgAAAJAAAACQCAYAAADnRuK4AABPQ0lEQVR42u29ebCl91ke+PzW7/vOdu
; /t7tt7a7EkS5axHUPs4AUMjjEYkoBtwpLJVoRKhSyVSmoyQzI1NTM1/2QSigwQCAEyyUwxYQhxymCy
; sS9mwOMNyzGYGFsylix1t3q5yznnW37L/PG+7+983Zastq2lJfWpul6k7tt9z3m/d3ne53le4Nbr1u
; vW69br1uvW69br1uvW69br1uvW69br1us5eylF//3lJ7fve9c7/8SVV+wuTo//+a3XtS996y0YBQ+A
; nIGXHpmdfctLjn/0VSe3F//r19z/yNlFs5UzoG8F0a0A+rzBA2DqjP66O49/9Gjt7UE79PccnaVvv+
; /Mv6mtRsr06269Ni9z6y24tnR9/V3Hv/e2+fTr7tyZxLuPzKsTkypOvb0HSp392MX9n0853wqiWwH0
; xNnnbXcd/ysv3936gaO1z+e2Jm534mG00kNM7bGmeu0jh+vf/vTe+pNaKeRbb9utEgYAEgxfeebIa1
; 91Yucnrq6H1jttT05rGKUwsRa3b0/rE9N69R0vO/ufXnZs/pKUM/StrvpWACkAKWecmFbNG88dfd/V
; dd83ztTHJxWcUVBKoYsJXYjYaVx9bj4Jb7/39H+ce+tulbJbJQxaKRit8E13n/h+b8xXDCnnl+/OzW
; 1bEzijURkDoxUm3mBirUrIYadxx7cqf/f7Pnv5XbeS0Is4gLQCUgbefMfx77j7yPwfHfRDODWvvbca
; jbPYqT0aZzCvLGLMOOwDEmAW3rUTb1990IWP/+GV5cde7P3Qi7KEUekCTs3q+SuOL35q2YfeGW1rq3
; F8UmHuLQAgpIQ+JCilsF077DQObUy1yrn/1ped+X/u2pkef7H3Qy+6AFKKJq6jja/eee+Z31mHFIac
; dWWMdkZDK4WtyuJo7TFzDk5rWK3QxoQuJGzXFrdvT/TuxPff9ao73rVVOZORoV6kHdGLroRppaCVwj
; e/9NSPb9f+rX1IAYA7s2hwz84MTmt4o5FyBhSFRswZ3mjMvEVMGftd0H1KceLMnUZh8pHz+7/4Yi1l
; 5sUWPClnvPG2Y9/4ZccX//jyum+t0dWJaYWtysFohYW3ONJ4zCuLuXeojUHjNJRSWIeI5RCwqByUUu
; Zy27d378y++jP76/c8fLB+9MUYRPrFEzw0st+5Pdl9zemdnz3ohtYZ7fsQEVJGZTQygMoaQClcbQPa
; ELEKEftdRB8SnNY4Ma1htIIGcGrW+Mbq/i+84txvHZ9W9YuxH3pRBJA0zXNv7TfcdeIXkLPuU7Z9TP
; r4tMaiskgAFt6hcQa11didetTWYOEtZt6gstQfrYaIIWUcnVSYOqOdNvrYpPZ/8RW3/dzUWftiw4de
; FCVMMd7zbfed/emdiX/zfhsGILvGGezUHlu1w/FpjYkz0Eoh5IwhZgAZKWeEDAwpQyvAGg2nFZZDxH
; KImDqr+xiHndq/dOr1/R+5sP8zLybuxws+gLRSyDnjtaeOvPGVJxbft9cNqwTUGQqLysJpA6sVamOw
; qBxm3mJiLSbOYqd2qK3GxDnUlkDFLkashwgFhal3CCkhZZiQ8urErHnV1W745YeuLv/oxdIPmRd25i
; F+z+6kqt9298n39SHZkLJXUEoC4uS0wpGmglIKtTWYOIM+JfQxoXIGMQN9SuhiRB8yjFaYeQetFQ66
; AKUUvNFYhmgMMByf+Ld/+PzeDy2HGF4MiegFG0Dy2VVGq3e+7PS7J878sTamDCgTc8aiomnLaI3aah
; ypHY5NPJzR2Ko85t7Cag0FoLEGNX9ppbAcArqQ4C1hRPtdgDNatSHlyprZduVe/eHzV3/qxYAOvWAD
; SErIn37pyf/+tsX0ry/70MaUfQYw9xZaady+NcGRxqGxlHWMpknMKg1iINL3SDkjpIw+JoSUYbTGVu
; 0QUsZqiNBKwRmNVYhaqdzuTqr7rdHrj13c/60XeikzL9TgSTnjDWePfs1rT+/85JW2b5FVHQHknLFd
; U4ZRvA+bOYN55bBdORilUBkNKGDiDIzSmDjKPpXVqCwF17IP6FOC0wrWaFxpB8y8xRCz7WJqzy2ab7
; iyHn79j/ZXD72Qg+gFN8YrxntOTqvZG88d/dWrbeiN0nXk8Xq79mhjRGMJcXZaYYgZERkxZwwpYRUi
; +pSgoKAUEFJGFyIOu4D9LiDlzE12hQzgsA/YqT0sZ6Ljk7p2Gv13vvzsr56Z17OU8wt2MHtBBZDi/6
; ytUV9/14mfDjmniKxDylBKwRmFidVYeAutFbqQ0DgLbzVm1iJnAhTnlUVtDXKmMV7++dQZbNWEFcWc
; cbXroaCwqKgMtjFxeQTmzuuJt+k77j/70401Ci/QfugFVcI0T11vvfP437jryPxvL/swKAUXUkbi7B
; NSxk7jy5hueDdmNeE/i8phYmm0N1qxEkNhyBk5A12gMV4rhcYaeKMRUsZBTyuOVYjoY8LEWb3sh2F3
; Ut8Xcrr48ccP3v9CLGXmhRM8CikDX3Fy+yted/bouw+GYaWVrkPKyACMUpg5QpUbZ9HFhJmzcJxxps
; 7AaI2pN+gizU8hZ8QMeGOgoOCtLtMYmK140AcYDdTGIKaM5RBwtPG43PZQSpkuxNWZRfPN55fdz3/2
; sH3B7cteECVMqKm7k6p50+3HfmMZYkgZdcoZMSXElLFVWQwpIUPBaaJsOKOxDhFGKSQAhtn1mhvomb
; OYOMpGVisKkD5irws47AM084RqY9CGiCEmnJrV6GLC1FHTXXtbT60N33Lvqd/YnVTNC23VYV4Y2Yc4
; Pt9675mfnlb2lX1IQSvYLiYoAFYrTDjb7NQeXUzwxmDqLBprcLTx0EqhsgYZtLbIyAwoZmh+zIymLF
; QZ2pdZpbAKCcshorEGzmi0IWM5RGzXHsshwmqtuhDDzNl6u/Yv+8CjV/7NC2nhap7/wUOl62vvOPaO
; e4/O/+dVH/uYsweAlDJSBo40HoBC4yzmlYE3tAPrU4JSQOMMUiLOjzMEDm5XvgCIU0/lDQAi40FtIG
; zIG43GGiilcNhHAMBW5bDXDWiMRsgZVmvTxdjvTqsviwkf/cTlw99/oZQy8/wPnowv213c8yfvPP7e
; VR/7kLPVCmqICUYRymy0htEKRycefcqAUtipHRpnMfMWVinETH1SyhR0WgEDrzRyVggpFxDRG+qFKk
; NBdcDI9JSpsKsQAADOKLQhcYZUqgtxuOfo7M89vL/+148t28svhCCyz/e+Z+atecudu+9dDjFkwCJD
; R/41Q044OZkgRMo0BAJmTL1DHzMO+wEnphVCyrBGY1G5UhJnfvPW1NZAKfozlQKGmLGOEZGyC6aORv
; eYMq6GiMoYzL3FH+2tMfUGh31GY40evLXtEMPb7z313k9dXZ4+6EMUUeOtDPRs4z0KqK1W3/6ys++a
; OvsVIecUczJGKQyM+zSOfjyrNY5OKFBSBnYnHhNLPdDUWZrSQAh0yhkJmXuhhCElJAAhJnQxIXGm8l
; aXMT7ljMMhoIsZc2cRMo31jsteGxLhSVAqxJRmlZvvNPaVH72w/28Snt96++dlABFFA/imu0/+/bt2
; pn/joA8toDxASgr5SI7UHkYpdClhq3KoDAWV0xptSMigER2gPmin8rBGozIaE2fhDZWrxpnyvz032i
; EltIG+AMAbWnP0KWOvGzD3FpXVeHzVYbv26CNNg1Yr3cbYHp/UX6aV6j5+6fC9MgTcCqBnaeJKGXjl
; 8a3733ju6L/b74eVUqqJKUEzNgNQCdK6jPdwRmEdEhbewRvqiY5NKjhN/U3MRBhrAy1Mcwa6SD3QEB
; OGlNFxEIAnO8KE6Hv1KWG/J0hgUVmsh4h1iJhVFoFtPSIj20YrG1JanZw133Bx2f/Mo4ftxedrP/S8
; 6oGEmrrTeP+m247+0qqPvYKqQ6JGtYsJRpGKonEGVgEJ1PtYreA0rSg4xiggNdBog6kzqJ0FMuA0oc
; zEScxorIHVugSZVoQJSWBlZBilseVpd7YaIkLO2Koc+pRxtR2wxf1V4r5pNaS6Nrn/ppee/KVP76/u
; uLLue+Ev3cpAz2TpAvBn7jn1g8em1ZvbECMAS7suTexAAAtWWKQM7NQeFVEt4I0mFqIxpTTJWE7fm/
; 63INcxJ8ScS8mijBRLFhIukRDyVyFi2Uc4qzFzDsshYkiEeC+HWHo3QsGNWoUYtyq3PXHm6O+e3/sP
; z8csZJ5PwZNyxmtP77z+1Se3f/SwH1qldBVThtY0Llu2EJs6CwX69VNnue9RWHiHBGA9BDijsV070s
; Bb0nxVmkZ+ZzQaq6E17ckmzqDhsb029P2MpkzXRQISEzK81michtUayyGgjxkTa9DziqOxFm2MMApw
; WmNI2XQhtLvT+nVX1v0vPnyw/szzLYieFwGkmNf88t3FXV//khMfWQ2xzwpV5j2XGPwMKWGr8vBWY0
; gZ27XDVuWwDPT0LyrH5UzTHow+xFI2hkROHForKlkJiJnG85AyhsToNE9nkqkmHFwpA8shog0RM2/h
; tMJeF2C0wtRZXO0GNNZAK3BAGXQxWwX0t21N/+r5ZfeT55fdFfU8Qqpv+h6IfAszjk+r6Tfcdfx3u5
; hSAqzKEJQXbYhwRgMgCqr0MVRaMiaWsooCcNhHGE3UjowMDWDqDBa1Q0wZMRHvWf5wlXOZzAQLcgwg
; pkylbTWQtsxpjdoYOK8YK0qo+c8+6EPZqa0CTW1dIPrHpZTsduPSt73s7O9eWH7y5IVVt3y+9EPm5s
; 8+tIN6x72n/u+tyr96HeIggZ8zTTZK0Qd2tKlQW43VEDGvHI40Hl2kzLFVUTbyvKqwTMPoRpkkJiAr
; wCqF2mpoKJZC05jdx4QuZvQxo4+RpT9Ujiaexv6YgYM+IKRcgMmr3YCJp9L3+LpHYw1SzliFiNoYhJ
; RVjGlwRjfblbvngYt7P/N8Wbne1AEkeM9rTu181StPbH/f4RBarVSVkJESoLXCeqCMQl4+RKvwxsCP
; GIe1IVrqOkR0MaEyhkuYoqxhDWbewijRkGkg02gfcybgUFPfY7VC7YgS4tmMIaSM9UBNtlIoq44+Jq
; xDxMRZGK1w2JOKw3Ams4rwqMZadDEZpXK7O61eddAPv/LpvdXzQhqkb+bSlXLGdu3c688cfffhEILR
; yoeUKLUz1dRpjW5ImDgNpzWutgO8IYwn5iwbcUy9xdxb3ppTA9zGhDZE5FGwEE5DAKNj8JC4Qan8mi
; 4mHPYDDvuAjvurqTNYVBa11bTS6AbEnHG08VAKuLTqUVmDrcphHSJq9h5SisrtjFQgvjE6vPmO4+/e
; qd3zwgXN3MzZRymFd9x76icWlXv9kHICssmZxnMAGCL1PtTT0IdtFOCZUei4Ga4Z0+ljAhQ107VkKE
; adDW/15UMLo8Y5gfogDcpOltckldVlXdHHjHWgsV2zxoz6HcpC9ah5tloTQh4iKqtx2EdMvMEQsxpS
; SjNnp0cm7uzvnt/7WeDmzkLm5gwealC/+vZj3/Ly3cU/POhDa7XyMbETD2cfo2lNcaT2mDriJButcG
; JKZPc2EJl9p/bwTE81WtHKgRHmlDMm3gIgYwSjaKSXPVdlNLwx3EQr3mlRwLQDke9Tpj5IVh5QCqs+
; Yh1JtTH3hAO1MWGb1ytX2h6Noxmm5yD1RqMNUWeV25PT5jWrED/yySvLj9/MpczcjJknZeCeI7OzX3
; fn8fcd9qG1RtdDStCgsZoCiFQTIrWBovVC4wwck728IZdV2VHFDCw82dd5DgzpWTJnn5QzlFZlkTok
; CjStCUoACN0mIHITaApAGyItTqWxdpqRaWrUJ86iDeT04Q1BCIG9h0oWImDTZuT27Lz58w8frP/FxV
; W3f7MG0U0VQDK6npzWs3e+7PQfDCm7rGBzykr6Hq1AqlBDYsA577aE+3xyVsNq2sgPKeNIQ8QwrymD
; eGsAZPT84VlFozcR6zV7BDnOPJpLo+GSpK9p7jt2LRtSQkrUNzWOeqcM4HAg1Hri6J9fWVNftKgcYg
; b2OtKSyQpmHSOMomCM/LzcuTP9rv966fBHDvrQ34zw0E0TQBuKhlHffv+Z36mMeUmbUjJKmSFSuQqJ
; oigjI6RU5DQxZ2hmHDpD73LFBPiJs+h5lNdQ2PJknOAYZbaGAidlKiV9oiw0xERNdkwIPOoPiXqonF
; Emv8pRebOagngdqQ8SgWJtdUGrjVaorWVzBmIA7DPto7IaV9ZDCdqQsspAskpNT8392x64cPBj8SY8
; tWBuptKVM/B1d+7+tTu2p9+9HEJrlPYp04enCNVDG2gMjxlFZZEZVDwxq1BbKgNtiGicxaLabN+lzK
; 0GGudDpOxQWV2a8MYabFWeS+NGEz9jnMcozcg4/Zl9oPF94JLa8NqDmAER+31AzsC8ot9/paUgmVcW
; baA+SkZ+bzTWvJLh9YzWKreLyp9LGZ/4xOXDj95spczcHMFDTfNrTu18+evOHv25wy70SusKAOMwKB
; QLajop+zhNS9KKcR7LvUzFATN1lsfuSBJmb7E9AhOBjIrZhn3ckOhlrSFriz4mBB77B1Z5QIEzjEHt
; DCoOmjYkLENEH2Jx/KisIe5QTGU6u7weCLB0GgddYA9Gg+UQaeMP8AQIq4D+5LT+s5fb4T2fPWwfvZ
; lK2XO+ypDJ5rbFZOfrXnL8g8su9lkpqwBqXnkPJmN4bTUyT2BTp9FFYL+PODN3mDqDLpA0eWIJl5El
; bBsoGA4GIrwaReizcJulx8qZKazXldfaGpgR8UvzeN2yRV7O1N0brTBzptBKlkPgrKmxU9GG/sKyw7
; xyaCxlJOIWaayGgCO1w+OrHtYoTL3F0CbAGDt1CG+/9/QHLyy7Iw8frK/IfvBFnYGk7/FGq2+7/+yv
; O6NPtSlCK2US9yKaCe+Zm+wupmJFt+QdmIzdIQEV9zQTZ5Ay0A6UfSqrcbQhaofhMkCcZpq4upiosU
; 6pbNrHXxkjglnK6FMkJw/uXyQQFYjUtg4bzvSESWcHvDObeAvFKw4Z/fe7AZYJ+z1jUKKOXQ9ROa1T
; RMaZefMnP3z+6k/cLCCjea5LV87AN9598u/csT35rmUfB6WUk8265cZZse2c05QpBJ9xhmgTM2ex3T
; jKNJFK3XbtS7mIvDOrrC7BYFiavF05eC4zQiSTiUu+RLFK/ZBFxb++sjSVhUTTWBcJF/JcUitLb+/h
; ELEaEiqrMffURO93A7ZqB0DhoA/IAJyhUtc4CiiBB7iB105hmHh726Jye//l4v7v3Az9kHnuShcFzy
; uOL176ptt3f/6gD61SqDLTJ8YlTp7GPibsMGi4ZlphYw0m7N9stYYzhEpPrClTk1EKW5XDTu3KcpSy
; Gv05LY/iPY/jldVI/MHJVxSPoBTL6D6WTVfWoLG0ygAH8pqzn1YKU09o+EFPkp8pj+/LIdKSVxtcbS
; kjDfyzyff3hoBPa7TpY2xPz5tvOr/sfuqxw/bSc82nVs9N5uG+Z6vZ+XMvv+1CO8QUka0CdMzU+zhN
; pcCw/YoC0U/nlUPNT+YqRCy8xel5jSFuRvCjjceicsgcJIHxoqmjhtkoxR6HBlMOPmnYxZHs+teEyf
; hKqSLvGZdCooJsJkZnVCG4taxeVYq+t9MKj697dCESJpQyDrrAq5NUBIuPHKxZ9UFZ7tK6h1YqXW37
; sBqi/tEPP3j84f31FRlCXhQZSI2C6B33nf7ZiTX3tCllDZjMT7ni5ijz4lKQZJIia3SJPujaaGzVvm
; A8FcuOF0xkZykNGmdwYlrB8T5L5MsKCikRPSOy5EdBlTF8/KWYXx1kKuP/5iQHy7hQ7WhZG3JGF1ga
; rejvNuFx/bAnem3tTCHfLyrLVJABU2/RBprYuihZtJQyVRuTlYI9VvtXf+ixvZ/MeO7wIfNcZJ8M4E
; 23HXv7y44t/sFBH1qjladFJpU1zY2tKk94Qm0tamcANkcYcoYzGscaD6t02ZJXljwOPS8sc1mQ0ocK
; kGKUfIDIfdUZVaTLjjGYcfmSJrzSvBdjHrTnPkix4mLg22J9TCUQGzZn6CKN91rRlFZZKlkxZcwrV6
; ACMXxQiiTSh30sfVDjDJZ9gFFKp5zbReXvjUgPfPLK6jnbl6nnonTdc2R6+s++7Owjh/3QAqqWeh/T
; xskr8ERUGVOe0KNNtZluFFE2xMPHa80KCpIrC4/HMDlsqyJL3sA9lpQ6N2IaKkUGVFNnr2EDZhDyLH
; hUAn0PBcBoFH8hqwVfItVGn2jq0tiAmDlnrAPt15zRCJFGfa2oPF9cdjjoA3ZqV5rrS6se5LqnxqUM
; h/3QXu1C/a8+8ukzf3hl+dnnopSZZztSG2vU2+89816j1W6foYyivkewHqNR7OWkv2gsla4+Zu5PiF
; F4pPFwmoKSmIUUFLWhKSqDegqjiRoiLmXk86PLUlWYh5nhgjjiPsuX4s5/HJSV1Zg6V0DEyGWrDREh
; JzhtiC8t01hP5coZAjmNUtjvBmrAncVeN5SF8DIQXjV1Fl2M5X10RqOLGSGmsps7Pavf+uELe/88xG
; d/tDfPXvahD+cb7zr5P5zbmnzneoiD1nCJgydx8Mi+KyRamIaUsPAWW7VDzMS5sUphp3GAoobbWw2v
; yMJFJDwiQa6NwdGmKuN8zyQyQZKHgjdRkHuWPDujihpV1hyWf1HkxjwUpw7qiTR7RjfOojIGGRkrBj
; ZzBoGDDDIe9nQyYepJCr3XDaitwXbt+EZHwNwT8Dj1lt1gKcNMrMGagkprhaG25vTC2+GjF/d/89ku
; ZebZK13Aq45v3f9Vtx9910E3tFqpCmxIkLEZh0MiYrJmtefMuyKNERWo2NQ1zNHpI23Wj9QeM6aago
; G/wPiP9DeVUF6NKbYspYTyFJYyTXTDSIkB0N8p8SLV8jK24u/juRQObMi5ZNDQW40pY0syxksmnTqC
; GooUWhvsjZar+10E/9WLqDImQBvKuj2VQZOR2xPT+q2X18PPPHKwflZVrurZyDwpA2fnzeK/efnZ82
; 1MSCB+V0wbDo7mfZRWipiGWpegOdJ4op2yBmyHEWUZdx0jx9t0hgmadVeGXVMX/JSXYM1UGhaVLQEu
; Xogzb1BpUzCicQ/kWZ2axtwhxrNyIaRRL6TZVrPgS2wZI3+3LqbC53ZaY9kHtOxspqFwYd2Jlh5rNq
; x69LAlpkCi/unyqseaZEjp6rrrVyHin3/ooROf2V/vS7/5vM5A8ubOvNXfcf/Z3/bWnO1S1lpBZ8Y2
; ZNIitJkANKs1+kRk80Vli3LUMiYy87agzCFlXlJqHKk9u8vTB9eGWFBjzY4atJknspfwnQkrYk40T3
; 3X90DSH4nOXQLEMhOxYg41uIdqY8I60rqjtrqIG4eYcTAEIBOYKBt4WtFYDImcPuYVucYe9JEl0kRq
; C0xys/x+hJyREpTRWiPDnZtP3vbAhb0f72PK6vlewhQ/ke+878w/Ozmr/9RhH3ulYIWSKuOpZpTZsD
; xZ+NDeUF9jlUbICUPO2KnpIIq4a0hZmzmS0IScuLRoeG2IQsqBNiRqPlPegIWC8zjudWbOorG2lDnP
; MuiKjRSsplIFtclCZXznQDNcgia85xoYle4jZSyhiLQjvnRjqXwNLAcyippuQcVXIWKn9liHxKUsF9
; PzNkRYo1XOua+cPnN84k9+5Pz+z6tnoZSZZ7LvyTnjdeeOvuWPn9z+gavS9wBFBbGpo6ooPSX71FZj
; u/JFKlOx5mruCbsRX56W2Xw7NY3kRmkkULAA1KQ6veE1U8nTpWcR8nwfMwcl/d6W/YDoiww0yYg8Fx
; czme5qxntqawssEJmT1IVEBg7MEzIswz7sSbEqvtLEXkzYqi0xCoaIbT6nsN8FbNeEFRlNa5iQKXtb
; Ps+wHiIaZ8wQU3tsUn/lkPJvPXh1+alnuh9Sz2Tpun1rcuQ7X37uUjuENgK1/HOhaciOS+TEA4+mCq
; JHZ+uUmEXiQ5eTAzP+2HHMGYMZb98NqzEU6N77zJE7q+AjmoWD27WnnkSrggEhZ/5Ar3vT+fuKYZVA
; DnGURfnsE69cNriQZpBRtvjyhnsewZcDrTAmYl7eDiQT4l3ZYReYZkJZbFE5nF92hZdUWVK4XlkPGD
; j7Xly1bcqq/rEPP3j0U1eWl59Jlat5RiKSxln1zvtO/0JlzG19ztCsO5aVgR79ULIi8EajSwlTZ7Fd
; O3YEy8U5rLKm9A0ZQB8SYgaONh6zyjJQh0ICm7DJk9OqjOGCBxnGj2LKrF6lsVzwnIEzU2DuNAUIod
; 1tTIiJJryQc3F4rR19yQ5sSKQ+DYnsXybXXfxZj+zwoGhCU4oa/MM+YIgJO011jZH5fhfQOFP+buUg
; DIgdqUDN/ipEfdt88oYPPnr1Xz2TLmjmmSpdX/+SE99z1870e1ZD7LWCg4yhPLkk3h8JrkPLTBS1aL
; HdzbSMXFQORycVjeYpl6AQUG+IrN/StA/zlvoZGXcHmv7YI9Fiiymmsr8S4vzUWdJ+Xf9lNCk8DDXl
; XpvSN1mjS5ZpeZWRM5XjZkT76PjfRw66GdvrLYeIPtEJKqUUrqyJGzSvHNZDuIbuCpD6NpBRFXqmrx
; iGFcjCWOs+xH5S2Ttn3pz/vccPPvBMlTLz9AZPoaa+9qtuO/bu/S60WaGS6BfvQikLkakOPa8shkSH
; bemUUsIQM++aVOHfeC4LPRs8LfjKjpS+kBL6QLDAuP9xRuGa0ZbVHUKa77jESMP9hF95g1B3I3qruK
; N55lFXPOmlon5NzPfRheKaWUPfp4yG/RbJ+DMUafR+P0BBYV457HcDhpQx8xb7Q8DcGyAD6yDENt78
; R+rjamfMKsT2tq3JN+934T9+Zn/9yDMRROrp/EYZwIlp1fylV9x+dUDWISadiYVBbzQbISQqaViHCG
; 8MuclnBteYrSclZoiEBZ2aNSwvJhCJ9kgJWzWtMwTmd1zGKkMkMHlChX6htcKR2qF2dExFxniJq+vp
; rOO+buZdoXLIz5u5HNMDksiggeSPhVFoNfVqAxPP0uh7OG6q20Arl4k1OOgDlkMgnyN2PNNKIcREKg
; 5DZepwiFgPAYdDJKovsxkurXpZBKer6z4d9CH96Ice3L6w6tZPtyuseTqj0ButvvW+Mz/XeHtvH1KA
; 2nCuAx+tzdxoDomWnQNnn5CJsrBV+4KlaF6UOmMw8aTtopMDlD2c1diuHCrWdQkzsE/k2TxlfEb6IP
; m+crag595HPIKkzxIYYfxVSjCvL+QrsPBQ8KvKaTZ42ChoxTMog30VjSnlRnhChG3pUuaIkpuxGhIm
; zmDqNK50AwsUDQ66gKm3SHwQGDlfk2U7woqU0ypAKX920XzFhx+7+q/T0ywNenoCiHGRd9x7+h+fW0
; z+4nqIvVLw4Ce0SHOkcVYKfSRDSqWImlFbzczCVJ5a2c6fmjfQUJSeM+ANPdmNNXS2KUrzKBot+qAC
; G2OKvt0ochCbV5S1nDFFPy+uHF4/+ds7sQbWqFKmamOuodcmoCxT20C7LijqWSbsatbzPbLA2jERPb
; YhYs2K1UVlsc/lbeEtsgL2u8BgpcJBR9gR8kaj1oZYRvqJo91ZykBttOlD7Cfe3nukcdP/cvHgF59O
; Ayvz9DTNwKtObH3Z684e+cllP6ygVL1pdXKhdaa8AQ2tIbzHcV2mW6WOJTY0N1itmH9jmLAlvB9Kwk
; f5XOXYbk76KemLvNYwmuGDlAu7sZDjYy7+0TnT062eIAOp0uhn9gniL7aMEdcQsn/RLPWhYWBImaQ+
; zLAUiIKmMeJLy9UgADgYIlIC6/03jmeNM9jvQsHLVkPA1BMXXLjeMkXKjXvCqbTZ74fVufnkTVfb4V
; 2PHKwvPF39kHk6+p7KaPVNd5/8TxrqaJ/LnpFujUbedCshaCkMiX4wxw201UQ2l3FXpMoxZRyfVWw6
; wP2PUeXMZGMJ45HyUbPW3XGp61O6hkQvrMFF7UpQWp7k5GEQctgTfUl5c3pjuiBNcc3noooRFWciya
; KNNcXerguZeU30Z84ronYcDqStp5JluGTRZaGQ6KRCYw1yIvxoVjlmL9AJhjbQbg2MhituEQCFShu1
; 34dwata88UOPXf2xQSgqz2UAaTZk+sa7T37vucXkz7cxRba7KU904i5ajth2McLyxKWZXyyIrNEaQ0
; 7FvEDGYAENFQjjCYkAv53alcvKZFRApWzO/Y8VJSnkcO4maw6JAjKNnlzLungZz6//ElsW4UCHAhAm
; psUS/dQZjUqMOa0pHKd1SEVdMmFjBii6v9pFmsaor6GMZRRdSVz2EV2iLKR4o79hHETMPO/KlOK9Ia
; HxE2eZ2J9hjNJAjs7os1u1bX/v8YP3Ph2rDvOllK6UgTecO/rW157e+Vf7fWgVrypoT5SQsiokdMF5
; 5AqyY3MEz3wdaWS90UiJxvST04rEgpFGesNlTHMmGcRBjHdPsp4wmpaMw4iiYXgimnuLqSfQUfM/R+
; a0j83C9Pqvnr2o5ecxrH6VJWo9WtrGkbaeHOrB+rANuUyWrdLUTxmJPuQPfKuiQH581RFmxJwgAhfJ
; +Z6s/Mg6hoSPmsuWLIjo5xNAtrHG9DG1Z+aTb+hC+u2H9laf/FJLmfpSStfRxtd/+ZW3XaEPCl5YEZ
; HTakwouIpo0p3RiCOGX2MJMDNKMbKc4XmaOMKUU196nIyYE7Yrj+OTiqkNmUHCXBxTj008wICmyHGE
; grFdkSix7LL4YQCVYsycedI31GgysEqylQdGSozxhp7prfxziM5NiGdCDZEssgqRdmMs/yGANaEdYq
; HmHvYBTism3NPROw3yR5LebcVrkavdQGS5mFA7g0urDvsdHchLyOnxZdcPMeGffvDBnYurrv1SVh3m
; i5m4mOCtv+P+s79RW3NHlzI03Ssh8EFINPzEyhhvtWZXMVO27tuVYzvdxDp1hXag2xZbtcMQE2+xye
; tQcQ9CoGEu5U3kL9KQDzGX3ZRjvZjnRl1czeRN2wQZBWgXxovUzZdkz5RQyq9jX2kpS56bY6G3rkNE
; xxOZMxpTS+BmYnZly1mosVSuukRgIpi2khLZwExGTXTK5LJ2MND3nXuLw35goyzw/Q7FwC5l6J6XwZ
; o/kQj4u49M3vLAhf1/GVLOX+xgZr6Y0gWl8C33nPr+M4vmW9dD6oHs5ET2MDp2ohUQEthFNW4aO+4D
; xooIxUCcG8ljxuBgKI7ytPuauE256FNG4r3Qdu0wY1NL6r02v4axKsoeI3CRboBR9po7V6TK46/Kmm
; I4rrkcggNq4L1YHxNlUW6cnVHle/lR0JRDd2w/Q8LBiAM+WEclVmPJlnlCg93rQmncV5ydamOwCgGe
; 1yUDy58OOjJTHxIJEBQbPwAZlTG6D7FvnL39aF1tPXBh7z9/saXMfOF9T8ZXnTv6TV9+avsHD/vQZq
; UqcPAk/pAI+VUlW0n26ZlpmBlNJKYh2aTIB9lGojEcaTyPzJRJKkMoslG0Lug5vQgOI1Kcymo+lpsL
; 0ituZJXVZdmZOVOKkHFgxDrhcwn1Y3PxxL++JFmlGCpgxzJnRlkILHhMRaIttA6aEmnDTlQRsASI+p
; h1TKhkrRMz9rpASLjKOOiHsvLZ6wbmdxsc9hELT7yonpe/yEAEULGPkvhETpwxB/3Qnpw1b8zABz51
; dfmJLyaI1BcycaUM3L0zPfmO+8482se4ihl1BrELlQIGvs4neE/mgFrHyLIb6hkcI7Ve62ueHFE87D
; Q8CfHqYeC9GAAcazx2+Hy37Kek/5g6i92pp1KTRixDPtndWEOKVe6XpLwa/jvLodwn6gdyCUbD2FbG
; eEFcesNrYANdmndBwaWcgUn2YhVMgsNAWcUa1IZIdHJrTEExvyjSgTu2DZY/+6CPGxOHPsJrhfPLth
; yJERrt5XVH5ZRWKOniumsrbSb/8oGHTv3BpcPHvlAqrPpCmuZF5exfesVtf+iMPjdQ86alARN6auSV
; BfhWhSxIu7jZexmtcHJak8qCG2sS30VMrMWZec2TDzXjXusyem/XDpYDS3jPQu1wrP8CKzwsN71KkQ
; LVselBGnGxhSdE1w9Jvpw/T/8nZptjebOwGgsXiRt4YUCO7V8kI4rmX0BINfr+9L6w9p/tiy8uO6K9
; VhZDpDFfBASPHKzZgkZzprIIMWHJezKrFAIoiNZ9xKW24wdHYb8Paa8d0Ib4mX/6wU/dfdjRvc78dJ
; YwkeS8/d7TP7w7qd7ShTRkwGKENse0QaW1BqtAVXlC7Ag0FOGfZcdUWTB6Q97JkRtwwn5UQY0ba8pk
; RmmaUrLQOMQPUVJxiJu9Vcgoza5SKFYqFa8jPF/Yqe3GH/r6r9oYzNiTsWIah1G6LGMLX4jR6cwNrB
; /Zv2ReyYhA0htSbVTsL33Y025NSl0XEwUBr25WAyHaW5VDBrDPciCtgL0uFFubwKc99zs6sZBBplUC
; lAZ+kyurVR/S4K05utvUx3/3wt6//0JKmbnR0vWVZ4581Vec2v7hwz60YEmOZCfRs8teRjRZwmORvY
; /8hu2K2IAtl6WJN4UcdXxalYWpQP81g4g1A28hgV1YDd+8YPsW/rNE5SHUVWuIAlKxiLD0PaPFqEAN
; YFL9k6HREiQCIAoSLqN8XaxfNr3WEDeBFXjpOWWOdQawjqlwnSsGEwOT6wkDosb5SjtAsdPIkjfxM5
; 4qL7cDLZsVlapZZdEOpMFfxUjyb+7DjFLFiAJQmDhrDvuhPTlvvrJP6VceunrjLvnqRprmU7N6/pde
; eft+H2I/5GzzyOE+Snrm5lkMm4rKM28aaK81tmsvV/uYzsonI7n8yCXkymqAnVATP6ln5g1xgtMGE9
; KgUuatwrGm4qaceTrMt1CMMh+bVNBMOUXeZFYJgIl86E/0ZlxHay0/v2TatLliF8eOZayGJWm0KpSL
; lsdqq3RZANO1n8CuJPT3UUphNRDZ3imNISUcMGY083Q+qgvEIV/2Ecs+FHBRfpYLy67QX0TssBwCDt
; oB4HLcxpQeX/Whsdr/0Ac+ufjM/vrgRlzQzFP1PVYrvPO+M/926sw9bUpARiHMqMw0DX7SCtdH0TTl
; lGKfHdpxkf6bzyzx+ciKRN+IiZajpEIgDGWsunBG3N2zLAiJFqE3d1Idv2GG+4zaykREvtGV1Ux/oJ
; ImpTHkjXG56No3PdLmK/JCtg+JPjie3oaCEYnhuOZ7GrS9BzYmVC17/lTGYGpNOfoi7q5KUeAIA3E5
; EG42Y+rGlXZgxYfFATfRWxV1E/vdgNrZog7xxqDjwzNyLUjAXasUIjYycm+UUhm5Txm3LSaveP9jV3
; 4q34ALmvl8gCFZsJz5h7dvTb5rPcQBgBt/Rzk1WZBYRowTj+Xi1iUSnp26KrunyprCZdE8eQng5Y0u
; Ij7JQMcmFR9EUUU1IbgQWbo4JlWhqCzk0G3m0jLzpqwf/OjUgRC/PAOUUE/wxQjzhI3MxcmsdsTvsW
; YT5CFtNPJCpbWa3DxkhJcNfcc/w8Ta0r8th1hsgWee/tlBRxSQKdN0yZiTdncrpsRu1R4ruWHPOzSS
; RRF1WKoCwEQ3pdGFWD6TiTO6i3GYV/b+I7VvPnpx/5eeysDKfD5VxZvvOPaOLz+1/YMHXWgzUJVsnk
; WasyHHG7ahU6DAcZos/6WEWbbQNZp4MyEneE7RIWUcYWqGYqKVOLh7rcrdUykXFTe/WgFDImZjwzQM
; LZMOb+SlDEuGlMDqYiw7rsTKUrFiMdiYKIy/FDeFKYljKwODI4KZPDzObCgdhrEv4UyvQiTViDWYWM
; tjPP3zthwNNmVD38XEUmgaPvbagKmnpny/C9B8QK/jXqq2urA9ndZYhoDt2uOgGwpnnYBfVY4RS2nz
; Vpu9NrS3b0++pgvpow/trX7/86HU6sn6npcemZ399vvPfmY5DKuY1USwgcz/MfCTI7izgkKX6I3RnB
; qF56wAHJ/S9ZzMaV56FVlwTvjNqflgiujSKXM57NT+mmYWoDQsR9zG/14ANMmimiCI0r+oUdMr5g4K
; QO3s5z1toqAw5XJRHMpG7k6Z+y3kzRJ20wuh4ELyIQojUnT7nvnffUg45L1WzWblQ8q0KOW2QtYkE0
; eL4YOOGuzGGpxftoRoO4t9XoMoBRx0EYf9UD5DzbThgz6QySfDI8s+4GrXr7TSk//rgT869/FLBw8/
; GT5kP7dXpJLyhnNHfnxIOcSs/Pg35tFFGyggJ8JchphgodGnCMVKBsGARL3pjUFSuUhz3ahkNfwmEb
; sQxfybhIWkDxccxbEtr7h1TJwpOJTX4vejSu8SeJWRedPNdj3Ft0cyjDeq2Mo82dMmawppSGX/Js26
; 7MesUZjIzo1xJrn0LBwlp8kbWjEdt2VDhsQYzawi+z0xK584w1zogHZkj7fHy9PKaPaZJkbm4RCKD/
; ayJ4+ldQgMfqYS9BOnsR42f8+Zs+hC8kNM4W13nfjx/3r58G35Sd6VJ0xOJ6f19C+/8rb9NqaUaOqi
; pxVAjEKhuLZDl2WkZdBwnH1OzWqkRCcgK7MBBUVAt1O7go6yzT+zEqmhPDmry58RRnYsIjM+UjtMmP
; aR+AOQbGoY4BOD8TGCnMpFZhrhG6M/b70XPrL0TGp00RCjTDx2LBvzjaS0SV8xjCAEsYYRIHIdApYD
; YUkTxqY6nrhki3/Y08Q2Z3nQwRD4fqvBZw/WBSLZ74igPyRCwa+uhyJ4FC55ymDjqk2ieHzVh6Sgf/
; j9n1w8fLBePtF78oRG43cfmb7BGa0Ph9BrpWzh+PCHJ3dJCfchVw0FhcQQvy97LwNr2CDcGMy0KuOl
; 5+wiunPHPcJ6SHAamDjaqOuyBOQLOVZdE0whb+56CYVClJxxpIfvomGbFhQKh2QqYjkSwPlU2IcEQG
; CedRj1UOVNVUSjdSMxo4zvPQsNZf/nDflICwF/zSxGKeeeA+egH2AVQR1aA1fWA0IiekrLvdOWJ0rw
; QT/AW9obHvSB74lQXyllTQHMKtj8XEQJieUs1qI2oQu5vn93/oaHD9a/cENNtNMKf/KO4z9urbpzIM
; BHS6+A0eIzjXAUxTRVz1nHjuiUR5uK7j4wib6x5aQR5t5iu/ZF20Tk9I0yFFA42vjSu8jvi9y0ixmC
; INsbEn3is1Cbk5Zz7+C1LiR6WbeQIQNt8zOuO/N03ZdQUOTJFRajTHPiPSRc6MC7rzVr5GMmyEOmMS
; f6fv415XQ4/7uBWYyC+XhNzfFyiMWncb8PSCBwdmAF68TRlv9S28NrgjramDDzFsshYOJJ+aq14tUS
; DSgLT7p8ca11yoBbyLMfPr/3f8Yb6YHObU1OHJv4r13HGIz8e675dMNBDCgztCLSt2Ky1cCL0gIaMm
; dXuMhtjLA5k8/zkIqnoFUGIRPDTj6QMcC3LpduFJtl0tPa9gm6UqyzUvBMEBMivxzVtVrBqKGUEjVy
; 5dgg1tTMPxVw5qyg2blkFfGcLvr7EUVWkHBp3CN7P665FZB1jiuybBrvMzvGblX08KyGWCRQW0ykv9
; IPxRP7oA8IOWG7Ig7VYQjYZvPOVYiYefo1Tm/+XiFv9HCa38OJ22TqrGCd0uH2rcnX3rk9OfEHlw7P
; P2UGet3Zo999bFq9NcQceZqliGT6A7lD5I2bGE9cjonPOWdYlt7K3kpG5crqkiUaq7HTVAXUE9VFYm
; 17TOQ4JvYsSW588bK2YtxlXhHOEVLGkIkXnTj7yIQ2cxYLzkDSE439fqgPIRpu+yRksjGpbGMhTE+X
; 8KWF90NOHRu1SB9Yr1bGfNqPTeR+a6J1Rp82rMoJ846WQ8SKL/jMmDAmUuiZp4/vajfAsPBxOQQMiX
; ZlVitcbgdMnCltQG0MlgPp7A+7WCZpOYBXMxlPso1RCJU16rCPj3zs8f33PWUT/T1//M7zXuvj3JBr
; eWqk+ZT6bxivkcljSNTniCElLR15uuGFaWDkOWTCNXanFSGivJqQwBApzJzNEcTvR0bJgQ25kYHdSU
; VSHH6CBJ+KIyrHnNl8QrOQTfRYZWr0Rqv++V4VB4ZgS7RI3hiV59JMb3qt63uhWO6xpjKNyc8nTMYh
; p6J6rXlDv+QpUkzP+5jo6g8/KCKLllIlPeR+P6CPGXNvcNjzZJaJSrvkNUktRDvOlJfXvVxqTArQl9
; vhwt/9xQdOPGUJc0ofZ+hCY8T9lS174mxB+xpd7OiMIn6u1xohRdSGGtohZrR8J8Jq8uCxmnqbEDO6
; nPhck2Znr4yc6Qk6NqnYkYswEDFkIEmNLZhIy6aaxb6FKawVaE0y87YsedPocMpYtyaWME8VQGRgpU
; vwYRSU4ngmZRGgYA4pYTVsmIpS3qbObs6GM09Ifu+CAcZV2Nwcaxwh9G1MuNIOMFrhaOOw1wUc9IGV
; LQp7LQGGi8phPVD/NWdSvtMaBgqrSFbC4gAbebIdItFeGoFGAJ3I2Ov4DU1hGUh0roqpGIyUCfFnLB
; LMmXqeIUoDHTFEctKCyhgiin/hmhu/hnEJugGhkEHocMcj/oTlvZm9c2RCqMzGaUPonAtWVyhoRs83
; vU/PJgOKkWuT1DXAoudNuGZtfG0MKqefklxeVKij/kEAUuJhUwZuEYsaV6gjxm1ARAmasovSGnO/kW
; hLthGWgUytl9sBRlG/phSwHqg53ylmVAMaNro66AfkDJyYVrjS9vz3NzjsB8wqizWT09YhYs34kdjo
; zR1hUKshiEl7utExXkNtbkxoBWRemJI8BehCLCQxNd62cwmTfVPPSlFpUvtAPn+n53VRHlhejIrmvI
; v0JM8cTR10fTABjD1RukchqYcEhBRHlnqUlfwIfx9rxiWjdiNaas4ZvUmY5KemRw1RFxXHRq2hyrbe
; ciPv7cYpXybENsRC+xV67oz9oiPTWwN7IVKgkgHEcoi42g6MLtM6aD0EBDak2HUej6961ssxT6jtYQ
; 1RQ5ZDQGRj0WVP/kKRnUO2+HqQ7OfodCfRXhtruCpE8ne6URxIOD668JtxDRINvppc82Q1Zgwen1TI
; IPf1xhoYiP+h4ieX+hOnNdvcZk6tqhgnZe5d1hyotdFlgmlHdia0tWYfoZH5wcDKicyYlJQu6kek1O
; lr1hqywMVTAIn16Fa8JCspi2PrvjhsyqqsMepyg2ODTI89piu+YS/7xMM+FCxLAMw2JKwGIpHNmf99
; yGT8ReVopzZsVhxXux5Oa5ya1Th/2JZTDodc8lYhYlY57Lc9upyKynVIGbXTSNmgY7PQGw6gmGSvQ2
; CT0gQiWk012WrNVisMGiZyZVcql05/UBnLEFAbU5rrISWcmNZorOF7EPSmiXhwHSI0SFkxZWs6gf9l
; qqp5iy9I6rInCzgtG+YRZTSP8Brh6QSG/FLhMStuhA2U3ez2niyAiMuUPod0JzIaodh67sPU54gVJb
; By6YUmjoyliIaaEDM9cF5rOEc8nlWgwPBGY5tN1/f7ULjcE2dwad0jsknnwPqwqbOojcbBEEpvKFjR
; EBNyJm3eUmvUlkBfqzWQSBgqqhRpJ24ogALzUjC2olMokLv0PKKy8FqjTRHHag/FvcvEkj/hcogIin
; qMBLZ4AWFBQqzSCqh4LdGPT2BDFbWpSIlDIBRqXlGQyR6KJi8etcPmGuKMTSzFM6ioNkcLUKF72KcQ
; RyXugRrunzZmWbl4BZUMlDOGIZWSJQ9AwxKdMTrdjqRAJOl2xRtp2Qckfv63a8fZnS8fOjoAM3AW0l
; CYVKTOCIkEmEDGlbZHxa4f51cdJmxwRZMZnVjYqi1WPdvQcLuQcoYlxmIp/U8ZQIHPIOXrF6ZKYZ2o
; XCUuV+MgmlhD7DaG51dMJ5g7i3WMOBgG7E4qtreV7KMw5RsYa75kM/cWW7UtT6wclrNKs/XdBkZYDW
; Fk4E0IsxMxI6PmTpFUOuZMuvt8Lb9F0HSjFMwN7MJ65jqPs1jZg/F6xHCjLndWMR7fY0abUsnwYtZQ
; G8K6hpjRhlB6tynbwoiXUGAH25kncv3V0aLVKoVL6x6e74i0A1FESG2r2LTK8EMe+ZRCgGUUvdOpNN
; VOa1K2gFzi6mRurIkOMbbemDpw6RJahJghyKK0i7EYBXQx4XhdoRqdra6tYVicmjHN/JPIXkApA13M
; UCApszem2LOt2ZbEFXBxY70rwSRq1DEW03F/lJFLSXPGwWjAQJebW0o4TbjWXCE8xQgmU5Uz5hpJtF
; JjeshGESsGVMW9tZRhvTHHZE7Sisu0N6pwgYRQNwT6+WhDT+Vpvwt8IFgXWGUVIqYMYtK/p0mVyHek
; t+tCwmcPW8y9ZTIZsF3Rfkzc/9sYS8+YeEpEToc3FEAPXl1+78t3t//3kGIPwIuGvM0RThFJTLJPFy
; OU0mxRS5mhsXRNpguJkeeEgyHgxLTGVmWxHhI6ZHh+I1Px+yGYfpd3Z+LBI64eTitUbtMQh5QRYkBW
; m97DW0ONPy9+M4AhJ4SIaxaeYvcwDoLpqH95KhK5iPPkzxA8Sb6zLCg9N86CEyVwBgqypc9FDiQWLz
; J1it7Na40585QEEwJQXEvWMeKwjQVb62PCxVVH9A6mdCilsFM7rNl/eoulQV0kmdRqCIXOq5VCY2lX
; VhuFqFSi69Tp4RsKoP9y8eBf3nNk/v1Ga0vNHFmIOE3lSmgaJEkx6ELETlON5LaEJodEGm1vFGqjmD
; 1IAZZAQdPL9MUrjsxvkozrU2cB5vL0MSETJQiLypFzFzbBVCY0QUGZJjoxuvx/OWYn/YZMbeCG/EZu
; bWkNNIbGc+N0kTIZZiqKg72gyENMWKcNQk1NvoLVppD7g1i/MJAoC1XhCa1DKLc+pFdbh1hA2a2agm
; /NLmdTPsy3x5v42vLSNWVs1+Tyf7XtsF3bwk1vrMVBP2DuHVIeyq5MA8Ep5X/pwYt/+4b4QArAN99z
; 6sfv2Jl+96qPvdbwbYjQWkNzg13xVKV5+SZiOzkOGxkaz2ykOee7ph3/O8u4UCqOG6TfPjGteFvPvo
; Ug1YI3qtz/6kPaeEVnlN2WlR0XT1sDS4kWlX3C7GPUhkymFLDwrihIn+ol5H1pLK/PRBoj00/+u8uf
; J8vUwHp+qYGCsJOPQCq0XsNyJMuA7LLfBM6US51s+2WxeqXtcdAHbNUOCnSTzDGleM1MR/Fo7JjVeN
; APjPsQ2ayLCVe7kGbe6IuH7af/5i888JLL6z7dCBKNT+4tf+TOnel3K4XUx0250qwB73llsQ4Rns9G
; ihVbZUgB0UbKPo2lxWEbEkl5+fevhsRiOV0MmxIHnNHkxCFUC9JM8aaeM5M3uuzoQsroc7rmKdesQx
; fDpsIo5H4kiG6cRfIrTvU3opMjrAYMGioYq8pYfn1TnTL1ZjFf6xbrjYaxjEyD6K1CYzVaodIaDeNN
; PXOdBWfaqmhlsWZSvtO63FyV0X6bSXrrgfjTmgPJsAHFaoi40obSSHtjimEViTszvFG9Vdr/9iOX/5
; cnCp4nZSROnTXfcf/ZC87o7TZGGECbkTxZtvBztjMRe9yQaKPstWK0lOxnzy2awuUp8mDm90R+w+be
; 4mjtyTRqZAxlNQWk3LCAAo6xk6v0DyIv3tA46Amv+XylnGUqPYr+3MvLC+824sensLcRZaxQZosWTH
; oh7rY1A5RGKVheLBc8ijOR/D5292daLXi9E4vWrmIAs+czUR2fzKQHEGyqmUtFuLjq0PECVX7PxJET
; 7OEQkDP9OVe7AchAw2Vu7mmYoaEH4fK6t3/zP39k8skry/UN9UBKAcshxE9cOfx7Lzs2/xcWqg051W
; rENJQS5tnThtDRwKYAlH0ML0mnjqYAA1WQ5zZsAsnzFCfMQ603vGZZAay5XGoFLPyGQFZOFaRcmljD
; o3Ft6an0Iy7OeHe18QWiKWPFKtAbCaAJzDXAIQDao3GIFoMJtWEvCFFL9nOidWvcBhPqI5WoxDyhyY
; h0NsSMwxDKLflFZRETmSqw+xhdt44Je13g9RGw6gkzWrCB6dVuINdYvzn6O/MWB93Anw9fRXS6V1D+
; Ixf2/7dPXV2un4xUr55MUDhxxrzzvtOfraw5Bqg0xGgrYwpBfot5yIEbu8yGAI55OjRyZ5xbTGAVje
; yE0Kqyd7mG9zzd8J7Henq6iLNxR516y5gTiipDSGJj8nrMIo3Ro5KyOS5XiGW8k5LjczfyqkbgZsa1
; Rg05X0s/Lz0aZ8qN53QuvZo03WLhZ83GmFyM0ospA2jykowjTbKUOc3CxJQzzi+7kt1b1qktKgdAYb
; /rywUkwo7o77nqI+behAil99v+8b/4ng+efXh/PTyZi5n6fKrUO7enZ998x7FP54SgtbJDSrrmEjav
; LKbWIjGhTHRY6yEW5t6MMQkBDTOnZvAmftMrEXtRgWXA1y0hZWFpFHBsUsFzAMpksuEqbT4sq4nOsD
; mmO/qA82ZSKgoIf2NWSRkoFr3CqZasp0pgqmsCKIIMOMeNc7n0zMoNLeh1zIUR6PSGZC8MAznyQlRd
; ml7FF7Fhl/0VU0MMr3gO+cCdnBdfDgEztojZawe+WUb86ZmzKaQYAG3/wa997PZfevDCw5/P8kU9la
; nCHzux9YbXnt55bx9za7WqiefsN4tUrvE9A2Hyz1POuGNrAq0p+wR2yiKHilwCyWjgWFPxdeJU2H5i
; lSIlQjx1dhpXnmY5XTB+ogN/CJVRxQtI4Vob382HjyJUnFhzQ2YCGUTwskIqkz+bA1LIZdLSGwDGbH
; wTRRcmDbwEVsziGbRB3IdR0AgxrZLpdggFWBX74CUftRN+VcrA+WXHYgSiccjFx4GBx7mnneNjhx2m
; 3iCE3NbO1D/4/k++8f/4yEO/ZRj2+CLNFSiI3nzH7t+5a2f6/THmVinUE28J3FKE9Wi1sY4jB1ZdiN
; 2Ksw04+9DTo8qd9z5uTnVL9hDRodwJkzKwVTnMKkvobtp8aLLxNtxwy1XAeWWv8QCSHkSkP6KwpROY
; 5gssYcy4UxvJDngyw6g3GmeXwKsMGRDUSGxYHpS4uTdv5PKi3ZzxFBnQkBKbL4BOZjLmNmHmpfCEhC
; pyMAw02VlDx+1y5skt48q6R0yAymiNUfV//tT5v/v3f/Vj/+SpgueGDKZkUvkzLz397u3KfnNl9OpI
; 4yeysvBi6J1Qzhq1IeHUrMKiIuh8KCexVfH1ESOq7cphp/EjJefmMK0Ek+ASjbN0pYaNFMa4TaGw8n
; +TG5m9hsZq9bjMyI5KEGN9wxmoGbl45OumsOvdW0m8yKsVo+CUhhlt6YvYkGVCcgna0RKNbWgS3w5B
; aRX6RA23tA+N25y/lL60ceTYcWndY84l64CPtUycxUp0ZZXFlVW/CilPPr23/Nm/8J4PfgtZ/uUbQu
; ZvyJ1s5q19+72nPnpm1tw3pNTWxtQy/dQ8KQgVoLYGW7VD5pPbAtHL8dyKFaBtpIOyAvc7I08rijXv
; OJiOTnyhXY6b7fEyVQSPDZtiSmkDrisvDBplEBNg6u0NWd2K1Z3ABvJ9NqbpehOs2FxQxKjHCaO+Tb
; Ku07q4nIjgUFQbXqtCyZXbH2In0zjarAtLU5pq4VmBwdiOtfdT5gntd3LczuCwC+3E2frBvdXH/8LP
; vv8Vjx624Uatf2/M4o6/2clpNXvbS07+4zOL5q+tQ0zeqJQzbJ9yIcOvQ8TupMKRxhdEFZx95DrPED
; f2/yemFd+xSMWoSppHzem352x1rPGl+ZR7pRj7AYknEIAjtUdlVRntZeweo9HSWFsGLm80A4nEOBP3
; 95rfF0cZqXCLympj3OTr8ncYY0KyexSxo9wc6yLRiy1v7nUhl8Xiq1iWoSEiI9OBPKux1w3Y7wIWFR
; tXMStRA2E5RL1TO/3hx/Z+9H/89d/7ew9c2Dv8QnwSb9hkU41ONb3p9mNf+/qzR3+F7HJz67SuWwYJ
; Z95ip/HMOqSnLzDGkVk4Z7ixrg0ZTimhnYpr6iiYRIoz9STNkbE3jZFdrcotDDAxnqxg2B0/bxxYr+
; fuCh+aVKn5hgJIvBevV6TiOt3ZmGwvtBEBEaVkESaEsu4QtmLHy86c5QqjKuuMPpB8qefBpOb1j/Sj
; DZdAOc8pB20O+IzmvHLoQ2wzUFdW40c+8Kk3f9/7PvGrOQPPiMnmOIgka9+zM9v9+juP/9utxn11F2
; JbW+PXIentxmF34pESiou6BFKx7QX94MIPkoCR1C+NsJhBDZEavi0ey8eTTGIqh3wg4Iyy3VBgGh6r
; i9VP+ZE3jbTQRm7klQBM7eZG/KYNozdHgmpMLsOoVyrjO5csFHZBKndaIw8a4x2Y2NIo3rGJPl6Wqr
; RioUWr2LwYReCtUiTTaQlHS6su9BNn6kcO29/4n3799771lx+6eHFsSPGM2Pw+kQVMY436xrtO/Lf3
; 7y7+Ed+rCrtTb6Vx9eZam7rx2YKcgZ2SfcRtdaN1L8HEvcR2JfffN1cB5SkflzShsc5lW8+lJOWxh/
; X40qDCxLEu/gZ7IM0XZcY3YMfccVF+SD8kqx3pv6RxFv63GsmkDR/Zo3shfGt+FDQF2Y6pUFuEEyTn
; EcQIS4EoyANjbV2MoQvJLiqHf/+Hj/133/srH/u+K22fb2TaeloDaDziA8BXnt559evPHfuF7dod26
; rtympdh5i0LAbHgSSN4W5TMQmcyE5x1DCb0Sgvrh1HG1+8l+Wpl73XGEwEl6+tyhWQcCwgTNj8XmEJ
; ikvrjTRBiUtezV4+MtXhOqLamGAvG3uxlhEWor3O8T7EjeBwI2fSm2uMYzk040UxJxz2pK2Xoy2Kb4
; X1kdiLldGpi6ntYpos+/D4D7z/k2/9iQ8/9OECdH4JN8G/pJNRm1E449SsnvyVV93+H2/bnnz1so+w
; Gq3W2g8cSEXznmkXdqT2ZRy2HGBh5AYvwaQ4NU+dpckE1zWkUtK4n5ElasM3URlrK+740kTLGgMMDE
; 5vQJUqGUikQ8VkfNxf5Q1XWlxfZUUhljACPA4j4FQmuLEhp2SaOLJ/8WVDH9Hxuc3ElFbDQsQuJjKm
; cib1IfUhp3q78vj4pf3f+O6f//DbHriwt5Ip8ku9J/+03D6UkrZTO/PWl5z4M685tf1DU2/P0JI0t1
; ppH1IuGWnmLHZZdSrwvtitFfcyPi8QE/kjLooz2LVXeMLoyZat/HblMPVmhMNsRqWxCUIoZpS6fNhP
; mYFY498Yc821ZLn8M35L00jqTGzEVAJOcx/kRl5DpbxxFlIsBPR8S6RLsXggGRYrOsbhZENPdjk6hZ
; j7mHM9dRaX2/6Rf/fxh//WD/x/n/q5Rw7W0fLtkafj9fRdbR7hBruTyr35jt0/9cdP7/yzmTMnyHUs
; 91Yb28WoG0umUkJVVRBLl2uzj2A6W/xr5YfWZQmq+MTS5uQAaerNNWZSkhXGC1WZ3nIGZo7uwecbtN
; eWfiWP0O2Y8jXl65psNyKFGc6qyJvFsYCOUlLEtUTIZYIJSV/pDGW/PqYClWgF1M6kkFKICX7qDC63
; w/l3/f7D3/OjH3ro5x+8uhzGD/vT9rnjaXyNSVTjQLo2I6E9Mamt1cr2JX0LmLYJpvE0sjupCoqMEY
; Ibs+A+hPRKQO7UjhvTTXP7RM5k0jjWjjlHN/i+anaNLyYNarNQlWwkD0IhsylV9l5l/TJa/OprLkOP
; 1jgMMjo2GxUzT8p+BIJm5LAOOYwzzrt+/+G/NQ6csSHE0/2ZP+2vJwgk++Y7dv/0a07t/PBW7U5t0Q
; 4mGYXeKm0zYDfXBTfBJBjKvLKl1ksDb5iGcU1Dzb3E3NvPhR9GDbUphDLFv94x2Hij2ZYIXkXVkVH8
; guIoUMdvsB2VLK02LmqlDKdcJjzLrE6jNwh/X06LE5IPIAwRISB7q5U2SuHSqnv0XR9/5G/86Icees
; +DV5fhmQycZzSAPl9Gesudu3/q9WePfPepWfONUr9Dykkr9I6DSWgaGUTfmHtTSsHYHiWMuMiys6us
; wXbtRvodFKL7NeuMvFHfkkvGF/aziWuaxoYRYBmwM+OpbPT3i+naNYYsU8v4XlSym0uMKER8yjRDzC
; FmeGeUFo3dQ1dX/+GXHzr/E//sg898xnlWA+jJAslohZcemc3+xOkjX/Xqk1t/9ey8+RbRNgXOTE5p
; mxXsduX4927OSkrqF/K6NJ/i+Hr9XkuPbVhGCLFck1549wW9EWQJbJhjnQsRblwWrx+NRW1RTmFyeM
; URBbe8P6MJM+cc+pRDyNk7rXXDMvA/uHTw7l958MKPvecTj/3mBx69eig042crcJ7VAHqyQJKm7r6j
; s/lrTu+87stPbv/1s/PmmyWYMpCONa5nCxerFDQydMzXmjlprWC5B1l4V8pLztdmmzz6YOWfaUVOsV
; /oGyEBpEY7Nrm8qMfY0AjcVNgEy7XTWEHXU045hYxA3Kbknda6Zh37H1w6/NlffPD8j/yHPzz/2+/7
; 7OWDNJqkzIgT/mx/ps/JS97Q8ZNqlMJLj1Jm+mMnFn/17iOzbzkxqVkcmGXsDlrnYJTWCkpDQedMJk
; gxozi4pydAhsXiv0xjXBZnX0QANYz0JnyuU5n8XUSpCl66yr6LJ6yEnFNETjEipZysUsqK1bHVJA//
; +KWDd//ygxd/7D2fePQ3P/DolcMxYixY1I3QLl5wAfRUwaQUcP+xxfwVxxcvuXtn9idesj19y+l59d
; Vz704IjjFscJWgNQJdO/TWaYWslJb1UyoN7ua2mXy4X0wJA8Cu8hvTUTPSxctUlqGSoj8o8a4p8Nhu
; oZS1o5MMgYhd5z+9v/6Njz1+8Esfu7D3vvc/euVTv/PIlYOx8efNEDQ3XQA9VTDJa3dS6Tu2J1v3HJ
; nd+crjW193+6L5mt1J9fqptwvZdi94AhsDZTnnoDQSZSLFd4OVVlBaIWPi7Bf8pk28JfYAkJBz4p1b
; 4mDVSqkCbVtNVnsTvpsRc8ZeF/Y/e7j6fz9xeflrv/3w5V984MLegx+/dLD36EH7ueK9myxobuoA+p
; xg4lHmCT2KtcKJaW3v2Jps331kdtddR6Zf+Ypj86+xypjdqftyp/W8cWbhRsZRIqEWrMlqhTkfqr3R
; V84o3j8F9OP/LZ0Z0Svifh/TwWOH7YdyRvzDq4e/9tGLB7/z0Qv7n/yDSwdXH95fh5A+V68nZfZmDZ
; rnTQA9Edq9GefxeRHVM/PGVkarU7N6fnxazU/N6rNn5s25Y5PqvnOL6uVWmd3btpo3Qak0MVp/oR9S
; 40yqrNEPXln+epfSxU9fXX3ssVX38Yf3Vp/5zP764fPL9uCP9tcHfUz5j/ZW4cm+j5S+fJ3X9K3Xrd
; et163Xrdet163Xrdet163Xrdet163Xrdfnvv5/nzek3zFbeJ0AAAAASUVORK5CYII=
; thumbnail end
;
; THUMBNAIL_BLOCK_END

; external perimeters extrusion width = 0.42mm
; perimeters extrusion width = 0.45mm
; infill extrusion width = 0.45mm
; solid infill extrusion width = 0.42mm
; top infill extrusion width = 0.42mm
; first layer extrusion width = 0.50mm

; EXECUTABLE_BLOCK_START
EXCLUDE_OBJECT_DEFINE NAME=c.stl_id_0_copy_0 CENTER=128,128 POLYGON=[[113.072,126.53],[113.646,123.646],[114.771,120.929],[116.405,118.484],[118.484,116.405],[120.929,114.771],[123.646,113.646],[126.53,113.072],[129.47,113.072],[132.354,113.646],[135.071,114.771],[137.516,116.405],[139.595,118.484],[141.229,120.929],[142.354,123.646],[142.928,126.53],[142.928,129.47],[142.354,132.354],[141.229,135.071],[139.595,137.516],[137.516,139.595],[135.071,141.229],[132.354,142.354],[129.47,142.928],[126.53,142.928],[123.646,142.354],[120.929,141.229],[118.484,139.595],[116.405,137.516],[114.771,135.071],[113.646,132.354],[113.072,129.47],[113.072,126.53]]
M73 P0 R9
M106 S0
M106 P2 S0
;TYPE:Custom
M104 S0 ; stops OrcaSlicer from sending temperature waits separately
M140 S0
SET_PRINT_STATS_INFO TOTAL_LAYER=125
PRINT_START EXTRUDER=210 BED=60 CHAMBER=0 TOOL=0
G90
G21
M83 ; use relative distances for extrusion
; filament start gcode
M106 P3 S200


M106 P2 S0
;LAYER_CHANGE
;Z:0.2
;HEIGHT:0.2
;BEFORE_LAYER_CHANGE
;0.2
G92 E0

G1 E-.8 F1800
SET_PRINT_STATS_INFO TOTAL_LAYER=125 CURRENT_LAYER=1
;_SET_FAN_SPEED_CHANGING_LAYER
SET_VELOCITY_LIMIT ACCEL=500
SET_VELOCITY_LIMIT ACCEL=10000
; EXECUTABLE_BLOCK_END

; filament used [mm] = 985.35
; filament used [cm3] = 2.37
; filament used [g] = 2.96
; filament cost = 0.06
; total filament used [g] = 2.96
; total filament cost = 0.06
; total layers count = 125
; estimated printing time (normal mode) = 9m 16s
; estimated first layer printing time (normal mode) = 0.565704s

; CONFIG_BLOCK_START
; accel_to_decel_enable = 0
; accel_to_decel_factor = 50%
; activate_air_filtration = 0
; activate_air_filtration_during_print = 1
; activate_air_filtration_on_completion = 1
; activate_chamber_temp_control = 0
; adaptive_bed_mesh_margin = 0
; adaptive_pressure_advance = 0
; adaptive_pressure_advance_bridges = 0
; adaptive_pressure_advance_model = "0,0,0\n0,0,0"
; adaptive_pressure_advance_overhangs = 0
; additional_cooling_fan_speed = 70
; additional_fan_full_speed_layer = 0
; align_infill_direction_to_model = 0
; alternate_extra_wall = 0
; auxiliary_fan = 1
; bbl_calib_mark_logo = 1
; bed_custom_model = 
; bed_custom_texture = 
; bed_exclude_area = 246x0,256x0,256x20,246x20
; bed_mesh_max = 99999,99999
; bed_mesh_min = -99999,-99999
; bed_mesh_probe_distance = 50,50
; bed_temperature_formula = by_highest_temp
; before_layer_change_gcode = ;BEFORE_LAYER_CHANGE\n;[layer_z]\nG92 E0\n
; best_object_pos = 0.5,0.5
; bottom_shell_layers = 3
; bottom_shell_thickness = 0.6
; bottom_solid_infill_flow_ratio = 1
; bottom_surface_density = 100%
; bottom_surface_filament_id = 0
; bottom_surface_pattern = monotonic
; bridge_acceleration = 50%
; bridge_angle = 0
; bridge_density = 100%
; bridge_flow = 1
; bridge_line_width = 100%
; bridge_no_support = 0
; bridge_speed = 50
; brim_ears_detection_length = 1
; brim_ears_max_angle = 125
; brim_flow_ratio = 1
; brim_object_gap = 0.1
; brim_type = auto_brim
; brim_use_efc_outline = 0
; brim_width = 5
; calib_flowrate_topinfill_special_order = 0
; chamber_minimal_temperature = 0
; chamber_temperature = 0
; change_extrusion_role_gcode = 
; change_filament_gcode = T[next_extruder] PURGE_LENGTH=[flush_length]\n; FLUSH_START\n; EXTERNAL_PURGE {flush_length_1+flush_length_2+flush_length_3+flush_length_4}\n; FLUSH_END
; close_additional_fan_first_x_layers = 1
; close_fan_the_first_x_layers = 1
; combine_brims = 0
; compatible_printers_condition = 
; complete_print_exhaust_fan_speed = 70
; cool_plate_temp = 35
; cool_plate_temp_initial_layer = 35
; cooling_tube_length = 0
; cooling_tube_retraction = 0
; counterbore_hole_bridging = none
; curr_bed_type = Textured PEI Plate
; default_acceleration = 10000
; default_bed_type = 4
; default_filament_colour = ""
; default_filament_profile = "Elegoo PLA @ECC"
; default_jerk = 0
; default_junction_deviation = 0
; default_print_profile = 0.20mm Standard @Elegoo CC 0.4 nozzle
; deretraction_speed = 30
; detect_narrow_internal_solid_infill = 1
; detect_overhang_wall = 1
; detect_thin_wall = 0
; different_settings_to_system = ;;
; disable_m73 = 0
; dont_filter_internal_bridges = disabled
; dont_slow_down_outer_wall = 0
; draft_shield = disabled
; during_print_exhaust_fan_speed = 70
; elefant_foot_compensation = 0.1
; elefant_foot_compensation_layers = 1
; elefant_foot_layers_density = 100%
; emit_machine_limits_to_gcode = 1
; enable_arc_fitting = 1
; enable_extra_bridge_layer = disabled
; enable_filament_ramming = 1
; enable_long_retraction_when_cut = 0
; enable_overhang_bridge_fan = 1
; enable_overhang_speed = 1
; enable_power_loss_recovery = printer_configuration
; enable_pressure_advance = 0
; enable_prime_tower = 0
; enable_support = 0
; enable_tower_interface_cooldown_during_tower = 0
; enable_tower_interface_features = 0
; enable_wrapping_detection = 0
; enforce_support_layers = 0
; eng_plate_temp = 0
; eng_plate_temp_initial_layer = 0
; ensure_vertical_shell_thickness = ensure_all
; exclude_object = 1
; extra_loading_move = 0
; extra_perimeters_on_overhangs = 0
; extra_solid_infills = 
; extruder_ams_count = 
; extruder_clearance_height_to_lid = 90
; extruder_clearance_height_to_rod = 36
; extruder_clearance_radius = 65
; extruder_colour = #F2754E
; extruder_offset = 0x0
; extruder_printable_area = 
; extruder_printable_height = 0
; extruder_type = Direct Drive
; extrusion_rate_smoothing_external_perimeter_only = 0
; fan_cooling_layer_time = 100
; fan_kickstart = 0
; fan_max_speed = 100
; fan_min_speed = 100
; fan_speedup_overhangs = 1
; fan_speedup_time = 0.5
; filament_adaptive_volumetric_speed = 0
; filament_adhesiveness_category = 0
; filament_change_extrusion_role_gcode = ""
; filament_change_length = 10
; filament_colour = #F2754E
; filament_cooling_before_tower = 10
; filament_cooling_final_speed = 3.4
; filament_cooling_initial_speed = 2.2
; filament_cooling_moves = 4
; filament_cost = 20
; filament_density = 1.25
; filament_diameter = 1.75
; filament_end_gcode = "; filament end gcode \n;M106 P3 S0\n"
; filament_extruder_variant = "Direct Drive Standard"
; filament_flow_ratio = 1
; filament_flush_temp = 0
; filament_flush_volumetric_speed = 0
; filament_ids = EPLAB00
; filament_is_support = 0
; filament_loading_speed = 28
; filament_loading_speed_start = 3
; filament_map = 1
; filament_map_mode = Auto For Flush
; filament_max_volumetric_speed = 21
; filament_minimal_purge_on_wipe_tower = 15
; filament_multitool_ramming = 0
; filament_multitool_ramming_flow = 10
; filament_multitool_ramming_volume = 10
; filament_notes = ""
; filament_printable = 3
; filament_ramming_parameters = "120 100 6.6 6.8 7.2 7.6 7.9 8.2 8.7 9.4 9.9 10.0| 0.05 6.6 0.45 6.8 0.95 7.8 1.45 8.3 1.95 9.7 2.45 10 2.95 7.6 3.45 7.6 3.95 7.6 4.45 7.6 4.95 7.6"
; filament_self_index = 1
; filament_settings_id = "Elegoo PLA @ECC"
; filament_shrink = 100%
; filament_shrinkage_compensation_z = 100%
; filament_soluble = 0
; filament_stamping_distance = 0
; filament_stamping_loading_speed = 0
; filament_start_gcode = "; filament start gcode\n{if  (bed_temperature[current_extruder] >55)||(bed_temperature_initial_layer[current_extruder] >55)}M106 P3 S200\n{elsif(bed_temperature[current_extruder] >50)||(bed_temperature_initial_layer[current_extruder] >50)}M106 P3 S150\n{elsif(bed_temperature[current_extruder] >45)||(bed_temperature_initial_layer[current_extruder] >45)}M106 P3 S50\n{endif}\n\n{if activate_air_filtration[current_extruder] && support_air_filtration}\nM106 P3 S{during_print_exhaust_fan_speed_num[current_extruder]} \n{endif}"
; filament_toolchange_delay = 0
; filament_tower_interface_pre_extrusion_dist = 10
; filament_tower_interface_pre_extrusion_length = 0
; filament_tower_interface_print_temp = -1
; filament_tower_interface_purge_volume = 20
; filament_tower_ironing_area = 4
; filament_type = PLA
; filament_unloading_speed = 90
; filament_unloading_speed_start = 100
; filament_vendor = Elegoo
; file_start_gcode = 
; filename_format = ECC_{nozzle_diameter[0]}_{input_filename_base}_{filament_name}_{layer_height}_{print_time}.gcode
; fill_multiline = 1
; filter_out_gap_fill = 0
; first_layer_flow_ratio = 1
; first_layer_print_sequence = 0
; first_x_layer_fan_speed = 0
; flush_into_infill = 0
; flush_into_objects = 0
; flush_into_support = 1
; flush_multiplier = 0.3
; flush_volumes_matrix = 0,280,280,280,280,0,280,280,280,280,0,280,280,280,280,0
; flush_volumes_vector = 140,140,140,140,140,140,140,140
; full_fan_speed_layer = 0
; fuzzy_skin = disabled_fuzzy
; fuzzy_skin_first_layer = 0
; fuzzy_skin_layers_between_ripple_offset = 1
; fuzzy_skin_mode = displacement
; fuzzy_skin_noise_type = classic
; fuzzy_skin_octaves = 4
; fuzzy_skin_persistence = 0.5
; fuzzy_skin_point_distance = 0.3
; fuzzy_skin_ripple_offset = 50%
; fuzzy_skin_ripples_per_layer = 15
; fuzzy_skin_scale = 1
; fuzzy_skin_thickness = 0.2
; gap_fill_flow_ratio = 1
; gap_fill_target = nowhere
; gap_infill_speed = 250
; gcode_add_line_number = 0
; gcode_comments = 0
; gcode_flavor = klipper
; gcode_label_objects = 0
; grab_length = 0
; gyroid_optimized = 0
; has_scarf_joint_seam = 0
; head_wrap_detect_zone = 
; high_current_on_filament_swap = 0
; hole_to_polyhole = 0
; hole_to_polyhole_threshold = 0.01
; hole_to_polyhole_twisted = 1
; host_type = elegoolink
; hot_plate_temp = 60
; hot_plate_temp_initial_layer = 60
; idle_temperature = 0
; independent_support_layer_height = 1
; infill_anchor = 400%
; infill_anchor_max = 40
; infill_combination = 0
; infill_combination_max_layer_height = 100%
; infill_direction = 45
; infill_jerk = 9
; infill_lock_depth = 1
; infill_overhang_angle = 60
; infill_shift_step = 0.4
; infill_wall_overlap = 15%
; inherits_group = ;;
; initial_layer_acceleration = 500
; initial_layer_infill_speed = 105
; initial_layer_jerk = 9
; initial_layer_line_width = 0.5
; initial_layer_min_bead_width = 85%
; initial_layer_print_height = 0.2
; initial_layer_speed = 50
; initial_layer_travel_acceleration = 100%
; initial_layer_travel_jerk = 100%
; initial_layer_travel_speed = 100%
; inner_wall_acceleration = 10000
; inner_wall_filament_id = 0
; inner_wall_flow_ratio = 1
; inner_wall_jerk = 9
; inner_wall_line_width = 0.45
; inner_wall_speed = 200
; input_shaping_damp_x = 0.1
; input_shaping_damp_y = 0.1
; input_shaping_emit = 0
; input_shaping_freq_x = 0
; input_shaping_freq_y = 0
; input_shaping_type = Default
; interface_shells = 0
; interlocking_beam = 0
; interlocking_beam_layer_count = 2
; interlocking_beam_width = 0.8
; interlocking_boundary_avoidance = 2
; interlocking_depth = 2
; interlocking_orientation = 22.5
; internal_bridge_angle = 0
; internal_bridge_density = 100%
; internal_bridge_fan_speed = -1
; internal_bridge_flow = 0.95
; internal_bridge_speed = 150%
; internal_solid_filament_id = 0
; internal_solid_infill_acceleration = 100%
; internal_solid_infill_flow_ratio = 1
; internal_solid_infill_line_width = 0.42
; internal_solid_infill_pattern = monotonic
; internal_solid_infill_speed = 250
; ironing_angle = 0
; ironing_angle_fixed = 0
; ironing_fan_speed = -1
; ironing_flow = 10%
; ironing_inset = 0
; ironing_pattern = rectilinear
; ironing_spacing = 0.15
; ironing_speed = 30
; ironing_type = no ironing
; is_infill_first = 0
; lateral_lattice_angle_1 = -45
; lateral_lattice_angle_2 = 45
; layer_change_gcode = SET_PRINT_STATS_INFO TOTAL_LAYER=[total_layer_count] CURRENT_LAYER={layer_num+1}
; layer_height = 0.2
; lightning_overhang_angle = 45
; lightning_prune_angle = 45
; lightning_straightening_angle = 45
; line_width = 0.42
; long_retractions_when_cut = 0
; long_retractions_when_ec = 0
; machine_end_gcode = PRINT_END\n
; machine_load_filament_time = 29
; machine_max_acceleration_e = 5000,5000
; machine_max_acceleration_extruding = 20000,20000
; machine_max_acceleration_retracting = 5000,5000
; machine_max_acceleration_travel = 20000,20000
; machine_max_acceleration_x = 20000,20000
; machine_max_acceleration_y = 20000,20000
; machine_max_acceleration_z = 500,200
; machine_max_jerk_e = 2.5,2.5
; machine_max_jerk_x = 9,9
; machine_max_jerk_y = 9,9
; machine_max_jerk_z = 3,3
; machine_max_junction_deviation = 0.01
; machine_max_speed_e = 30,30
; machine_max_speed_x = 500,200
; machine_max_speed_y = 500,200
; machine_max_speed_z = 20,20
; machine_min_extruding_rate = 0,0
; machine_min_travel_rate = 0,0
; machine_pause_gcode = PAUSE
; machine_start_gcode = M104 S0 ; stops OrcaSlicer from sending temperature waits separately\nM140 S0\nSET_PRINT_STATS_INFO TOTAL_LAYER=[total_layer_count]\nPRINT_START EXTRUDER=[nozzle_temperature_initial_layer] BED=[bed_temperature_initial_layer_single] CHAMBER=[chamber_temperature] TOOL={initial_tool}\n
; machine_tool_change_time = 0
; machine_unload_filament_time = 28
; make_overhang_printable = 0
; make_overhang_printable_angle = 55
; make_overhang_printable_hole_size = 0
; manual_filament_change = 0
; master_extruder_id = 1
; max_bridge_length = 10
; max_layer_height = 0.32
; max_resonance_avoidance_speed = 120
; max_travel_detour_distance = 0
; max_volumetric_extrusion_rate_slope = 0
; max_volumetric_extrusion_rate_slope_segment_length = 3
; min_bead_width = 85%
; min_feature_size = 25%
; min_layer_height = 0.08
; min_length_factor = 0.5
; min_resonance_avoidance_speed = 70
; min_skirt_length = 0
; min_width_top_surface = 50%
; minimum_sparse_infill_area = 15
; mmu_segmented_region_interlocking_depth = 0
; mmu_segmented_region_max_width = 0
; notes = 
; nozzle_diameter = 0.4
; nozzle_flush_dataset = 0
; nozzle_height = 2.5
; nozzle_hrc = 0
; nozzle_temperature = 210
; nozzle_temperature_initial_layer = 210
; nozzle_temperature_range_high = 240
; nozzle_temperature_range_low = 190
; nozzle_type = hardened_steel
; nozzle_volume = 107
; nozzle_volume_type = Standard
; only_one_wall_first_layer = 0
; only_one_wall_top = 1
; ooze_prevention = 0
; other_layers_print_sequence = 0
; other_layers_print_sequence_nums = 0
; outer_wall_acceleration = 5000
; outer_wall_filament_id = 0
; outer_wall_flow_ratio = 1
; outer_wall_jerk = 9
; outer_wall_line_width = 0.42
; outer_wall_speed = 160
; overhang_1_4_speed = 0
; overhang_2_4_speed = 50
; overhang_3_4_speed = 30
; overhang_4_4_speed = 10
; overhang_fan_speed = 100
; overhang_fan_threshold = 50%
; overhang_flow_ratio = 1
; overhang_reverse = 0
; overhang_reverse_internal_only = 0
; overhang_reverse_threshold = 50%
; parallel_printheads_bed_exclude_areas = 
; parallel_printheads_count = 1
; parking_pos_retraction = 0
; part_cooling_fan_min_pwm = 0
; physical_extruder_map = 0
; post_process = 
; precise_outer_wall = 0
; precise_z_height = 0
; preferred_orientation = 0
; preheat_steps = 1
; preheat_time = 30
; pressure_advance = 0.024
; prime_tower_brim_width = 3
; prime_tower_enable_framework = 0
; prime_tower_flat_ironing = 0
; prime_tower_infill_gap = 150%
; prime_tower_skip_points = 1
; prime_tower_width = 35
; prime_volume = 45
; print_compatible_printers = "Elegoo Centauri Carbon 0.4 nozzle"
; print_extruder_id = 1
; print_extruder_variant = "Direct Drive Standard"
; print_flow_ratio = 0.97
; print_order = default
; print_sequence = by layer
; print_settings_id = 0.20mm Standard @Elegoo CC 0.4 nozzle
; printable_area = 0x0,256x0,256x256,0x256
; printable_height = 256
; printer_extruder_id = 1
; printer_extruder_variant = "Direct Drive Standard"
; printer_model = Elegoo Centauri Carbon
; printer_notes = 
; printer_settings_id = Elegoo Centauri Carbon 0.4 nozzle
; printer_structure = corexy
; printer_technology = FFF
; printer_variant = 0.4
; printing_by_object_gcode = 
; process_change_extrusion_role_gcode = 
; purge_in_prime_tower = 0
; raft_contact_distance = 0.1
; raft_expansion = 1.5
; raft_first_layer_density = 90%
; raft_first_layer_expansion = 2
; raft_layers = 0
; reduce_crossing_wall = 0
; reduce_fan_stop_start_freq = 1
; reduce_infill_retraction = 0
; relative_bridge_angle = 0
; required_nozzle_HRC = 3
; resolution = 0.012
; resonance_avoidance = 0
; retract_before_wipe = 0%
; retract_length_toolchange = 0
; retract_lift_above = 0
; retract_lift_below = 255
; retract_lift_enforce = All Surfaces
; retract_restart_extra = 0
; retract_restart_extra_toolchange = 0
; retract_when_changing_layer = 1
; retraction_distances_when_cut = 18
; retraction_distances_when_ec = 10
; retraction_length = 0.8
; retraction_minimum_travel = 0.8
; retraction_speed = 30
; role_based_wipe_speed = 0
; scan_first_layer = 1
; scarf_angle_threshold = 155
; scarf_joint_flow_ratio = 1
; scarf_joint_speed = 100%
; scarf_overhang_threshold = 40%
; seam_gap = 10%
; seam_position = aligned
; seam_slope_conditional = 1
; seam_slope_entire_loop = 0
; seam_slope_inner_walls = 1
; seam_slope_min_length = 0
; seam_slope_start_height = 0
; seam_slope_steps = 10
; seam_slope_type = none
; set_other_flow_ratios = 0
; silent_mode = 0
; single_extruder_multi_material = 1
; single_extruder_multi_material_priming = 0
; single_loop_draft_shield = 0
; skeleton_infill_density = 25%
; skeleton_infill_line_width = 100%
; skin_infill_density = 25%
; skin_infill_depth = 2
; skin_infill_line_width = 100%
; skirt_distance = 2
; skirt_height = 1
; skirt_loops = 0
; skirt_speed = 50
; skirt_start_angle = -135
; skirt_type = combined
; slice_closing_radius = 0.049
; slicing_mode = regular
; slow_down_for_layer_cooling = 1
; slow_down_layer_time = 4
; slow_down_layers = 0
; slow_down_min_speed = 20
; slowdown_for_curled_perimeters = 0
; small_area_infill_flow_compensation = 0
; small_area_infill_flow_compensation_model = 0,0;"\n0.2,0.4444";"\n0.4,0.6145";"\n0.6,0.7059";"\n0.8,0.7619";"\n1.5,0.8571";"\n2,0.8889";"\n3,0.9231";"\n5,0.9520";"\n10,1"
; small_perimeter_speed = 50%
; small_perimeter_threshold = 0
; solid_infill_direction = 45
; solid_infill_rotate_template = 
; sparse_infill_acceleration = 100%
; sparse_infill_density = 15%
; sparse_infill_filament_id = 0
; sparse_infill_flow_ratio = 1
; sparse_infill_line_width = 0.45
; sparse_infill_pattern = rectilinear
; sparse_infill_rotate_template = 
; sparse_infill_speed = 200
; spiral_finishing_flow_ratio = 0
; spiral_mode = 0
; spiral_mode_max_xy_smoothing = 200%
; spiral_mode_smooth = 0
; spiral_starting_flow_ratio = 0
; staggered_inner_seams = 0
; standby_temperature_delta = -5
; start_end_points = 30x-3,54x245
; supertack_plate_temp = 35
; supertack_plate_temp_initial_layer = 35
; support_air_filtration = 1
; support_angle = 0
; support_base_pattern = default
; support_base_pattern_spacing = 2.5
; support_bottom_interface_spacing = 0.5
; support_bottom_z_distance = 0.2
; support_chamber_temp_control = 1
; support_critical_regions_only = 0
; support_expansion = 0
; support_filament = 0
; support_flow_ratio = 1
; support_interface_bottom_layers = 2
; support_interface_filament = 0
; support_interface_flow_ratio = 1
; support_interface_loop_pattern = 0
; support_interface_not_for_body = 1
; support_interface_pattern = auto
; support_interface_spacing = 0.5
; support_interface_speed = 80
; support_interface_top_layers = 2
; support_ironing = 0
; support_ironing_flow = 10%
; support_ironing_pattern = rectilinear
; support_ironing_spacing = 0.1
; support_line_width = 0.42
; support_material_interface_fan_speed = -1
; support_multi_bed_types = 0
; support_object_first_layer_gap = 0.2
; support_object_skip_flush = 0
; support_object_xy_distance = 0.35
; support_on_build_plate_only = 0
; support_parallel_printheads = 0
; support_remove_small_overhang = 1
; support_speed = 150
; support_style = default
; support_threshold_angle = 30
; support_threshold_overlap = 50%
; support_top_z_distance = 0.2
; support_type = normal(auto)
; symmetric_infill_y_axis = 0
; temperature_vitrification = 45
; template_custom_gcode = 
; textured_cool_plate_temp = 40
; textured_cool_plate_temp_initial_layer = 40
; textured_plate_temp = 60
; textured_plate_temp_initial_layer = 60
; thick_bridges = 0
; thick_internal_bridges = 1
; thumbnails = 144x144/PNG
; thumbnails_format = PNG
; time_cost = 0
; time_lapse_gcode = 
; timelapse_type = 0
; tool_change_on_wipe_tower = 0
; top_bottom_infill_wall_overlap = 5%
; top_shell_layers = 5
; top_shell_thickness = 1
; top_solid_infill_flow_ratio = 1
; top_surface_acceleration = 2000
; top_surface_density = 100%
; top_surface_filament_id = 0
; top_surface_jerk = 9
; top_surface_line_width = 0.42
; top_surface_pattern = monotonicline
; top_surface_speed = 200
; travel_acceleration = 10000
; travel_jerk = 12
; travel_slope = 3
; travel_speed = 500
; travel_speed_z = 0
; tree_support_angle_slow = 25
; tree_support_auto_brim = 1
; tree_support_branch_angle = 45
; tree_support_branch_angle_organic = 40
; tree_support_branch_diameter = 2
; tree_support_branch_diameter_angle = 5
; tree_support_branch_diameter_organic = 2
; tree_support_branch_distance = 5
; tree_support_branch_distance_organic = 1
; tree_support_brim_width = 3
; tree_support_tip_diameter = 0.8
; tree_support_top_rate = 30%
; tree_support_wall_count = 0
; upward_compatible_machine = 
; use_3mf = 0
; use_firmware_retraction = 0
; use_relative_e_distances = 1
; volumetric_speed_coefficients = ""
; wall_direction = ccw
; wall_distribution_count = 1
; wall_generator = classic
; wall_loops = 2
; wall_maximum_deviation = 0.025
; wall_maximum_resolution = 0.5
; wall_sequence = inner wall/outer wall
; wall_transition_angle = 10
; wall_transition_filter_deviation = 25%
; wall_transition_length = 100%
; wipe = 1
; wipe_before_external_loop = 0
; wipe_distance = 1.2
; wipe_on_loops = 0
; wipe_speed = 100%
; wipe_tower_bridging = 10
; wipe_tower_cone_angle = 30
; wipe_tower_extra_flow = 100%
; wipe_tower_extra_rib_length = 0
; wipe_tower_extra_spacing = 100%
; wipe_tower_filament = 0
; wipe_tower_fillet_wall = 1
; wipe_tower_max_purge_speed = 90
; wipe_tower_no_sparse_layers = 0
; wipe_tower_rib_width = 8
; wipe_tower_rotation_angle = 0
; wipe_tower_type = type2
; wipe_tower_wall_type = rib
; wipe_tower_x = 15.000
; wipe_tower_x = 15
; wipe_tower_y = 220.000
; wipe_tower_y = 220
; wiping_volumes_extruders = 70,70,70,70,70,70,70,70,70,70
; wrapping_detection_gcode = 
; wrapping_detection_layers = 20
; wrapping_exclude_area = 
; xy_contour_compensation = 0
; xy_hole_compensation = 0
; z_hop = 0.4
; z_hop_types = Auto Lift
; z_offset = 0
; zaa_dont_alternate_fill_direction = 0
; zaa_enabled = 0
; zaa_min_z = 0.05
; zaa_minimize_perimeter_height = 35
; first_layer_bed_temperature = 60
; bed_shape = 0x0,256x0,256x256,0x256
; first_layer_temperature = 210
; first_layer_height = 0.200
; CONFIG_BLOCK_END


